udistrital/sga_cliente

- src/assets/i18n/es.json
Ajuste tilde tarea sea_cliente#190
> ajuste tilde

- src/assets/i18n/es.json
ajuste año de publicación por año
> ajuste ano de publicacion por ano

- src/app/pages/proyecto_academico/list-proyecto_academico/list-proyecto_academico.component.html
- src/app/pages/proyecto_academico/list-proyecto_academico/list-proyecto_academico.component.scss
- src/app/pages/proyecto_academico/list-proyecto_academico/list-proyecto_academico.component.ts
- src/app/pages/proyecto_academico/registro-proyecto_academico/registro-proyecto_academico.component.html
- src/assets/i18n/en.json
- src/assets/i18n/es.json
Se realizan ajustes sobre el componente Listar Proyectos Academicos
fix #194
> Se realizan ajustes sobre el componente Listar Proyectos

- src/app/@core/data/models/calendario-academico/actividad.ts
- src/app/@core/data/models/calendario-academico/calendario.ts
- src/app/@core/data/models/calendario-academico/proceso.ts
- src/app/pages/calendario-academico/actividad-calendario-academico/actividad-calendario-academico.component.html
- src/app/pages/calendario-academico/actividad-calendario-academico/actividad-calendario-academico.component.spec.ts
- src/app/pages/calendario-academico/actividad-calendario-academico/actividad-calendario-academico.component.ts
- src/app/pages/calendario-academico/calendario-academico-routing.module.ts
- src/app/pages/calendario-academico/calendario-academico.component.scss
- src/app/pages/calendario-academico/calendario-academico.component.ts
- src/app/pages/calendario-academico/calendario-academico.module.ts
- src/app/pages/calendario-academico/def-calendario-academico/def-calendario-academico.component.html
- src/app/pages/calendario-academico/def-calendario-academico/def-calendario-academico.component.scss
- src/app/pages/calendario-academico/def-calendario-academico/def-calendario-academico.component.spec.ts
- src/app/pages/calendario-academico/def-calendario-academico/def-calendario-academico.component.ts
- src/app/pages/calendario-academico/detalle-calendario/detalle-calendario.component.html
- src/app/pages/calendario-academico/detalle-calendario/detalle-calendario.component.scss
- src/app/pages/calendario-academico/detalle-calendario/detalle-calendario.component.spec.ts
- src/app/pages/calendario-academico/detalle-calendario/detalle-calendario.component.ts
- src/app/pages/calendario-academico/list-calendario-academico/list-calendario-academico.component.html
- src/app/pages/calendario-academico/list-calendario-academico/list-calendario-academico.component.spec.ts
- src/app/pages/calendario-academico/list-calendario-academico/list-calendario-academico.component.ts
- src/app/pages/calendario-academico/proceso-calendario-academico/proceso-calendario-academico.component.html
- src/app/pages/calendario-academico/proceso-calendario-academico/proceso-calendario-academico.component.spec.ts
- src/app/pages/calendario-academico/proceso-calendario-academico/proceso-calendario-academico.component.ts
- src/app/pages/pages-menu.ts
- src/app/pages/pages-routing.module.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
> Mockups para crear calendarios academicos

- src/app/@core/data/models/calendario-academico/actividad.ts
- src/app/@core/data/models/calendario-academico/calendario.ts
- src/app/@core/data/models/calendario-academico/proceso.ts
- src/app/@core/utils/nuxeo.service.ts
- src/app/pages/calendario-academico/actividad-calendario-academico/actividad-calendario-academico.component.html
- src/app/pages/calendario-academico/actividad-calendario-academico/actividad-calendario-academico.component.ts
- src/app/pages/calendario-academico/calendario-academico.component.scss
- src/app/pages/calendario-academico/calendario-academico.module.ts
- src/app/pages/calendario-academico/def-calendario-academico/def-calendario-academico.component.html
- src/app/pages/calendario-academico/def-calendario-academico/def-calendario-academico.component.ts
- src/app/pages/calendario-academico/proceso-calendario-academico/proceso-calendario-academico.component.html
- src/app/pages/calendario-academico/proceso-calendario-academico/proceso-calendario-academico.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
Conectividad del formulario de creación del Calendario académico con la respectiva base de datos.
fix #209
> Merge Feature/calendario guardado

- src/app/pages/calendario-academico/def-calendario-academico/def-calendario-academico.component.ts
- src/environments/environment.test.ts
- src/environments/environment.ts
> La correción anterior no tuvo el efecto deseado, 

- src/app/pages/calendario-academico/proceso-calendario-academico/proceso-calendario-academico.component.ts
En la creación de procesos. #209
> Se corrige el llenado del tipo de recurrencia 

- src/app/pages/calendario-academico/def-calendario-academico/def-calendario-academico.component.html
- src/app/pages/calendario-academico/def-calendario-academico/def-calendario-academico.component.ts
> fix: Se corrige error de creación de procesos y descarga de archivo

- src/app/pages/calendario-academico/list-calendario-academico/list-calendario-academico.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
> fix: ajuste cliente para inhabilitar un calendario y su relacion en el modelo E/R

- src/app/pages/derechos-pecuniarios/consultar-conceptos/consultar-conceptos.component.ts
- src/app/pages/derechos-pecuniarios/definir-conceptos/definir-conceptos.component.ts
> fix: Se agrega carga de costos de los conceptos. 

- src/app/pages/calendario-academico/def-calendario-academico/def-calendario-academico.component.ts
- src/app/pages/calendario-academico/detalle-calendario/detalle-calendario.component.ts
> fix: ajuste modulo calendario

- src/app/@core/data/models/calendario-academico/calendario.ts
- src/app/pages/calendario-academico/detalle-calendario/detalle-calendario.component.html
- src/app/pages/calendario-academico/detalle-calendario/detalle-calendario.component.ts
fix: ajuste detalle y lista de calendario
> fix: ajuste detalle y lista de calendario

- src/app/pages/calendario-academico/detalle-calendario/detalle-calendario.component.html
- src/app/pages/calendario-academico/detalle-calendario/detalle-calendario.component.ts
fix: ajuste detalle calendario
> fix: ajuste detalle calendario

- src/app/pages/calendario-academico/calendario-proyecto/calendario-proyecto.component.ts
- src/app/pages/calendario-academico/detalle-calendario/detalle-calendario.component.ts
fix: ajuste calendario y detalle calendario
> fix: ajuste calendario y detalle calendario

- src/app/pages/calendario-academico/actividad-calendario-academico/actividad-calendario-academico.component.ts
- src/app/pages/calendario-academico/def-calendario-academico/def-calendario-academico.component.ts
- src/app/pages/calendario-academico/detalle-calendario/detalle-calendario.component.ts
- src/app/pages/calendario-academico/list-calendario-academico/list-calendario-academico.component.html
- src/app/pages/calendario-academico/list-calendario-academico/list-calendario-academico.component.ts
fix: Se realizan pequeños ajustes para mejorar la funcionalidad del módulo calendario. #296
> fix: Se realizan pequeños ajustes

- src/app/pages/calendario-academico/list-calendario-academico/list-calendario-academico.component.ts
> fix: ajuste lista calendario

- src/app/pages/idiomas/list-idiomas/list-idiomas.component.ts
fix: Se corrige un fallo en la carga y registro de idiomas causado por la migración de datos a terceros_crud. #334
> fix: Se corrige un fallo en la carga y registro de idiomas

- src/app/pages/experiencia_laboral/crud-experiencia_laboral/crud-experiencia_laboral.component.ts
- src/app/pages/experiencia_laboral/list-experiencia_laboral/list-experiencia_laboral.component.html
- src/app/pages/experiencia_laboral/list-experiencia_laboral/list-experiencia_laboral.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
fix: ajuste modulo experiencia laboral
> fix: ajuste modulo experiencia laboral

- src/app/@core/data/users.service.ts
- src/app/@theme/components/header/header.component.ts
- src/app/pages/info_persona/crud-info_persona/crud-info_persona.component.ts
- src/app/pages/inscripcion/inscripcion.module.ts
- src/app/pages/inscripcion/preinscripcion/preinscripcion.component.ts
- src/app/pages/inscripcion_multiple/crud-inscripcion_multiple/crud-inscripcion_multiple.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
fix: Se corrige error de carga de información personal cuando el usuario no tiene datos en modulo preinscripción. #356
> fix: Se corrige error de carga de informacion personal 

- src/app/pages/calendario-academico/def-calendario-academico/def-calendario-academico.component.ts
- src/app/pages/calendario-academico/detalle-calendario/detalle-calendario.component.html
- src/app/pages/calendario-academico/detalle-calendario/detalle-calendario.component.ts
fix: Pequeños ajustes en modulo calendario. #296
> fix: Pequeños ajustes en modulo calendario. #296

- src/app/pages/calendario-academico/actividad-calendario-academico/actividad-calendario-academico.component.html
- src/app/pages/calendario-academico/def-calendario-academico/def-calendario-academico.component.ts
- src/app/pages/calendario-academico/list-calendario-academico/list-calendario-academico.component.ts
- src/app/pages/experiencia_laboral/crud-experiencia_laboral/crud-experiencia_laboral.component.ts
- src/app/pages/experiencia_laboral/crud-experiencia_laboral/form-experiencia_laboral.ts
- src/app/pages/experiencia_laboral/list-experiencia_laboral/list-experiencia_laboral.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
> fix: ajuste clonar calendario

- src/app/app.module.ts
fix: Se retira configuracion localizada de fechas por conflictos
> fix: Se retira configuracion localizada de fechas

- src/environments/environment.dev.ts
- src/environments/environment.prod.ts
- src/environments/environment.test.ts
hotfix:ajuste de version en el servicio de documentos en todos los environment
> hotfix:ajuste de version en el servicio de documentos en todos los environment

- src/app/pages/idiomas/crud-idiomas/crud-idiomas.component.html
- src/app/pages/idiomas/crud-idiomas/crud-idiomas.component.ts
- src/app/pages/idiomas/list-idiomas/list-idiomas.component.html
- src/app/pages/idiomas/list-idiomas/list-idiomas.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
feat: Función PUT para actualizar información de idiomas. #351
> feat: Feature/idiomas put

- src/app/pages/calendario-academico/actividad-calendario-academico/actividad-calendario-academico.component.ts
fix: uniformidad en nombres de propiedades
> fix: uniformidad en nombres de propiedades

- src/app/pages/inscripcion_multiple/crud-inscripcion_multiple/crud-inscripcion_multiple.component.html
- src/app/pages/inscripcion_multiple/crud-inscripcion_multiple/crud-inscripcion_multiple.component.ts
fix: ajuste mostrar info despues de select preinscripcion proyecto
> fix: ajuste mostrar info despues de select preinscripcion proyecto

- .gitignore
- src/app/pages/experiencia_laboral/list-experiencia_laboral/list-experiencia_laboral.component.ts
fix: ajuste cliente para  mostrar informacion de experiencia laboral
> fix: ajuste cliente para  mostrar informacion de experiencia laboral

- src/app/pages/experiencia_laboral/crud-experiencia_laboral/crud-experiencia_laboral.component.ts
- src/app/pages/experiencia_laboral/list-experiencia_laboral/list-experiencia_laboral.component.html
- src/app/pages/experiencia_laboral/list-experiencia_laboral/list-experiencia_laboral.component.ts
fix: ajuste cliente con funcion put experiencia laboral
> fix: ajuste cliente con funcion put experiencia laboral

- src/app/@theme/components/dinamicform/dinamicform.component.ts
- src/app/pages/formacion_academica/crud-formacion_academica/crud-formacion_academica.component.ts
- src/app/pages/formacion_academica/list-formacion_academica/list-formacion_academica.component.html
- src/app/pages/formacion_academica/list-formacion_academica/list-formacion_academica.component.ts
feat: ajuste de la funcion put, correccion del formato de fechas se actualiza la tabla cuando se guarda o actualiza
> feat: ajuste de la funcion put, correccion del formato de fechas se actualiza la tabla cuando se guarda o actualiza

- src/app/managers/errorManager.ts
- src/app/pages/experiencia_laboral/crud-experiencia_laboral/crud-experiencia_laboral.component.ts
- src/app/pages/experiencia_laboral/list-experiencia_laboral/list-experiencia_laboral.component.html
- src/app/pages/experiencia_laboral/list-experiencia_laboral/list-experiencia_laboral.component.ts
- src/app/pages/inscripcion_multiple/crud-inscripcion_multiple/crud-inscripcion_multiple.component.html
- src/app/pages/inscripcion_multiple/crud-inscripcion_multiple/crud-inscripcion_multiple.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
fix: ajuste preinscripcion, validacion generacion recibo
> fix: ajuste preinscripcion, validacion generacion recibo

- src/app/app.module.ts
- src/app/pages/calendario-academico/actividad-calendario-academico/actividad-calendario-academico.component.ts
- src/app/pages/calendario-academico/calendario-academico.module.ts
- src/app/pages/calendario-academico/def-calendario-academico/def-calendario-academico.component.ts
- src/app/pages/calendario-academico/detalle-calendario/detalle-calendario.component.ts
fix: Se corrige bug que causaba desfase en fechas de un día de diferencia. #378
> fix: Se corrige bug que causaba desfase en fechas 

- src/app/@theme/components/dinamicform/dinamicform.component.html
- src/app/pages/solicitudes/actualizacion-datos/actualizacion-datos.component.ts
- src/app/pages/solicitudes/actualizacion-datos/form-actualizacion-datos.ts
- src/app/pages/solicitudes/actualizacion-nombres/form-actualizacion-nombres.ts
- src/app/pages/solicitudes/dialogo-soporte/dialogo-soporte.component.ts
fix: Se realizan correcciones a los mockups de solicitudes. #355
> fix: Se realizan correcciones a los mockups de solicitudes. #355

- src/app/pages/inscripcion_multiple/crud-inscripcion_multiple/crud-inscripcion_multiple.component.ts
fix: ajuste preinscripcion gurdar persona_id y random en recibo_inscripcion_id
> fix: ajuste preinscripcion gurdar persona_id y random en recibo_inscripcion_id

- src/app/pages/documento_programa/crud-documento_programa/crud-documento_programa.component.ts
- src/app/pages/documento_programa/list-documento_programa/list-documento_programa.component.ts
fix: se corrige acceso al id de la inscripción por el session storage para documentos de programa. #390
> fix: se corrige acceso al id de la inscripción por el session storage

- src/app/pages/info_persona/crud-info_persona/crud-info_persona.component.ts
- src/app/pages/inscripcion/crud-inscripcion_multiple/crud-inscripcion_multiple.component.ts
- src/app/pages/inscripcion/inscripcion_general/inscripcion_general.component.ts
- src/assets/i18n/es.json
fix: control de errores cuando no hay informacion en inscripcion
> fix: control de errores cuando no hay informacion en inscripcion

- src/app/@core/data/models/inscripcion/recibo_pago.ts
- src/app/@theme/components/link-download/link-download.component.ts
- src/app/pages/inscripcion/crud-inscripcion_multiple/crud-inscripcion_multiple.component.ts
feat: Se agrega funcionalidad para mostrar recibo de pago de inscripción y se hacen ajustes. #417
> feat: Mostrar recibo de pago

- src/app/@core/data/models/inscripcion/propuesta_grado.ts
- src/app/pages/descuento_academico/crud-descuento_academico/crud-descuento_academico.component.ts
- src/app/pages/descuento_academico/view-descuento_academico/view-descuento_academico.component.html
- src/app/pages/descuento_academico/view-descuento_academico/view-descuento_academico.component.ts
- src/app/pages/experiencia_laboral/view-experiencia_laboral/view-experiencia_laboral.component.html
- src/app/pages/experiencia_laboral/view-experiencia_laboral/view-experiencia_laboral.component.ts
- src/app/pages/formacion_academica/view-formacion_academica/view-formacion_academica.component.html
- src/app/pages/formacion_academica/view-formacion_academica/view-formacion_academica.component.ts
- src/app/pages/idiomas/view-idiomas/view-idiomas.component.ts
- src/app/pages/inscripcion/inscripcion_general/inscripcion_general.component.html
- src/app/pages/inscripcion/inscripcion_general/inscripcion_general.component.ts
- src/app/pages/produccion_academica/view-produccion_academica/view-produccion_academica.component.ts
- src/app/pages/propuesta_grado/view-propuesta_grado/view-propuesta_grado.component.html
- src/app/pages/propuesta_grado/view-propuesta_grado/view-propuesta_grado.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
fix: ajuste modulo perfil y put de inscripcion
> fix: ajuste modulo perfil y put de inscripcion

- angular.json
- package-lock.json
- package.json
- src/app/@core/data/models/admision/tipo_criterio.ts
- src/app/@theme/components/checkbox-assistance/checkbox-assistance.component.html
- src/app/@theme/components/checkbox-assistance/checkbox-assistance.component.spec.ts
- src/app/@theme/components/checkbox-assistance/checkbox-assistance.component.ts
- src/app/@theme/theme.module.ts
- src/app/pages/admision/admision-routing.module.ts
- src/app/pages/admision/admision.module.ts
- src/app/pages/admision/evaluacion-aspirantes/evaluacion-aspirantes.component.html
- src/app/pages/admision/evaluacion-aspirantes/evaluacion-aspirantes.component.scss
- src/app/pages/admision/evaluacion-aspirantes/evaluacion-aspirantes.component.spec.ts
- src/app/pages/admision/evaluacion-aspirantes/evaluacion-aspirantes.component.ts
- src/app/pages/inscripcion/crud-inscripcion_multiple/crud-inscripcion_multiple.component.ts
- src/app/pages/pages-menu.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
Feat: modulo de evaluacion de aspirantes
> Feat: modulo de evaluacion de aspirantes

- package-lock.json
hotfix: Ajuste de package-lock.json por perdida de corchete
> hotfix: Ajuste de package-lock.json por perdida de corchete

- package-lock.json
- package.json
- src/app/pages/inscripcion/crud-inscripcion_multiple/crud-inscripcion_multiple.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
feat: Se realiza proceso de inscripción con generación de recibo de pago. udistrital/sga_mid#255
> feat: Se realiza proceso de inscripción con generación de recibo

- src/app/@core/data/models/proyecto_academico/nivel_formacion.ts
- src/app/pages/admision/asignacion_cupos/asignacion_cupos.component.html
- src/app/pages/admision/asignacion_cupos/asignacion_cupos.component.ts
- src/app/pages/admision/criterio_admision/criterio_admision.component.html
- src/app/pages/admision/criterio_admision/criterio_admision.component.ts
- src/app/pages/admision/evaluacion-aspirantes/evaluacion-aspirantes.component.ts
- src/app/pages/calendario-academico/calendario-proyecto/calendario-proyecto.component.html
- src/app/pages/calendario-academico/calendario-proyecto/calendario-proyecto.component.ts
- src/app/pages/calendario-academico/def-calendario-academico/def-calendario-academico.component.html
- src/app/pages/calendario-academico/def-calendario-academico/def-calendario-academico.component.ts
- src/app/pages/calendario-academico/list-calendario-academico/list-calendario-academico.component.ts
- src/app/pages/inscripcion/crud-inscripcion_multiple/crud-inscripcion_multiple.component.html
- src/app/pages/inscripcion/crud-inscripcion_multiple/crud-inscripcion_multiple.component.ts
- src/app/pages/inscripcion/inscripcion_general/inscripcion_general.component.ts
- src/app/pages/proyecto_academico/crud-proyecto_academico/crud-proyecto_academico.component.ts
- src/app/pages/proyecto_academico/modificar-proyecto_academico/modificar-proyecto_academico.component.ts
- src/app/pages/tipo_inscripcion/crud-tipo_inscripcion/crud-tipo_inscripcion.component.html
- src/app/pages/tipo_inscripcion/crud-tipo_inscripcion/crud-tipo_inscripcion.component.ts
- src/app/pages/tipo_inscripcion/crud-tipo_inscripcion/form-tipo_inscripcion.ts
- src/app/pages/tipo_inscripcion/list-tipo_inscripcion/list-tipo_inscripcion.component.html
- src/app/pages/tipo_inscripcion/list-tipo_inscripcion/list-tipo_inscripcion.component.ts
feat: Se agrega consulta de niveles de formación del esquema de proyecto_academico. #455
> feat: Se agrega consulta de niveles de formación

- src/app/pages/admision/dialogo-documentos/dialogo-documentos.component.ts
- src/app/pages/admision/evaluacion-documentos-inscritos/evaluacion-documentos-inscritos.component.html
- src/app/pages/admision/evaluacion-documentos-inscritos/evaluacion-documentos-inscritos.component.scss
- src/app/pages/admision/evaluacion-documentos-inscritos/evaluacion-documentos-inscritos.component.ts
- src/app/pages/documento_programa/view-documento_programa/view-documento_programa.component.html
- src/app/pages/documento_programa/view-documento_programa/view-documento_programa.component.scss
- src/app/pages/documento_programa/view-documento_programa/view-documento_programa.component.ts
- src/app/pages/inscripcion/perfil/perfil.component.html
- src/app/pages/inscripcion/perfil/perfil.component.ts
- src/app/pages/solicitudes/solicitudes.component.scss
feat: guardado de aprobacion y observacion en el Documento revisado. #466
> feat: guardado de aprobacion y observacion en el Documento

- src/app/pages/admision/admision.module.ts
- src/app/pages/asignacion_cupo/crud-asignacion_cupo/crud-asignacion_cupo.component.ts
- src/app/pages/inscripcion/inscripcion-routing.module.ts
- src/app/pages/inscripcion/inscripcion.module.ts
fix: se arreglan errores de build
> fix: se arreglan errores de build

- src/app/@core/data/models/documento/soporte_documento_aux.ts
- src/app/pages/documento_programa/list-documento_programa/list-documento_programa.component.ts
- src/app/pages/documento_programa/view-documento_programa/view-documento_programa.component.html
- src/app/pages/documento_programa/view-documento_programa/view-documento_programa.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
fix: ajuste estado documento solicitado
> fix: ajuste estado documento solicitado

- src/app/pages/admision/dialogo-documentos/dialogo-documentos.component.html
- src/app/pages/admision/dialogo-documentos/dialogo-documentos.component.ts
- src/app/pages/admision/evaluacion-documentos-inscritos/evaluacion-documentos-inscritos.component.ts
- src/app/pages/documento_programa/view-documento_programa/view-documento_programa.component.ts
fix: Se agrega cargado de datos existentes de revisión en el dialogo. #466
> fix: Se agrega cargado de datos existentes de revision

- package-lock.json
- src/app/pages/admision/evaluacion-documentos-inscritos/evaluacion-documentos-inscritos.component.html
- src/app/pages/info_persona/crud-info_persona/crud-info_persona.component.ts
- src/app/pages/inscripcion/perfil/perfil.component.html
- src/app/pages/inscripcion/perfil/perfil.component.ts
- src/app/pages/inscripcion/preinscripcion/preinscripcion.component.html
- src/app/pages/propuesta_grado/view-propuesta_grado/view-propuesta_grado.component.ts
Fix: Ajuste evaluacion de documentos
> Fix: Ajuste evaluacion de documentos

- src/app/pages/admision/criterio_admision/criterio_admision.component.ts
- src/app/pages/inscripcion/crud-inscripcion_multiple/crud-inscripcion_multiple.component.ts
fix: se corrigen pequeñas fallas
> fix: se corrigen pequeñas fallas

- src/app/@core/data/google.service.ts
- src/app/@core/data/models/correo/invitacion.ts
- src/app/@core/data/models/correo/invitacionTemplate.ts
- src/app/pages/admision/evaluacion-documentos-inscritos/evaluacion-documentos-inscritos.component.ts
- src/environments/environment.dev.ts
- src/environments/environment.prod.ts
- src/environments/environment.test.ts
- src/environments/environment.ts
fix: envio de correo cuando el documento tiene observaciones
> fix: envio de correo cuando el documento tiene observaciones

- src/app/@core/store/services/list.service.ts
- src/app/pages/admision/asignacion_cupos/asignacion_cupos.component.html
- src/app/pages/admision/asignacion_cupos/asignacion_cupos.component.ts
- src/app/pages/descuento_academico/crud-descuento_academico/crud-descuento_academico.component.ts
- src/app/pages/documento_programa/list-documento_programa/list-documento_programa.component.ts
- src/app/pages/formacion_academica/list-formacion_academica/list-formacion_academica.component.ts
- src/app/pages/inscripcion/crud-inscripcion_multiple/crud-inscripcion_multiple.component.ts
- src/app/pages/produccion_academica/list-produccion_academica/list-produccion_academica.component.ts
- src/app/pages/propuesta_grado/crud-propuesta_grado/crud-propuesta_grado.component.ts
- src/assets/i18n/es.json
fix: ajustes generales modulo inscripcion
> fix: ajustes generales modulo inscripcion

- src/app/pages/solicitudes/actualizacion-datos/actualizacion-datos.component.ts
- src/app/pages/solicitudes/actualizacion-nombres/actualizacion-nombres.component.ts
- src/assets/i18n/es.json
fix: llamado funcion mid, ajuste de fechas udistrital/sga_mid#272
> fix: llamado funcion mid, ajuste de fechas udistrital/sga_mid#272

- src/app/@core/utils/spagoBIAPI/spagoBIService.js
- src/app/pages/pages-menu.ts
- src/app/pages/reportes/inscripciones/admision-proyecto/admision-proyecto.component.html
- src/app/pages/reportes/inscripciones/admision-proyecto/admision-proyecto.component.scss
- src/app/pages/reportes/inscripciones/admision-proyecto/admision-proyecto.component.spec.ts
- src/app/pages/reportes/inscripciones/admision-proyecto/admision-proyecto.component.ts
- src/app/pages/reportes/reportes-routing.module.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
fix: creacion reporte admitidos por proyecto
> fix: creacion reporte admitidos por proyecto

- src/app/pages/admision/criterio_admision/criterio_admision.component.ts
- src/app/pages/admision/evaluacion-aspirantes/evaluacion-aspirantes.component.ts
- src/app/pages/solicitudes/actualizacion-datos/actualizacion-datos.component.ts
fix: se agrega periodo donde hacía falta
> fix: se agrega periodo donde hacía falta

- src/app/pages/admision/asignacion_cupos/asignacion_cupos.component.html
- src/app/pages/admision/asignacion_cupos/asignacion_cupos.component.ts
- src/app/pages/admision/listado_aspirantes/listado_aspirante.component.html
- src/app/pages/admision/listado_aspirantes/listado_aspirante.component.ts
- src/app/pages/asignacion_cupo/crud-asignacion_cupo/crud-asignacion_cupo.component.html
- src/app/pages/asignacion_cupo/crud-asignacion_cupo/crud-asignacion_cupo.component.ts
- src/app/pages/asignacion_cupo/crud-asignacion_cupo/form-asignacion_cupo_posgrado.ts
- src/app/pages/pages-menu.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
> fix: ajustes generales bugs

- src/app/pages/admision/asignacion_cupos/asignacion_cupos.component.ts
- src/app/pages/admision/listado_aspirantes/listado_aspirante.component.html
- src/app/pages/admision/listado_aspirantes/listado_aspirante.component.ts
- src/app/pages/asignacion_cupo/crud-asignacion_cupo/crud-asignacion_cupo.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
fix: ajuste metodo para cambiar estado de inscritos a admitidos
> fix: ajuste metodo para cambiar estado de inscritos a admitidos

- src/app/@theme/components/checkbox-assistance/checkbox-assistance.component.ts
- src/app/pages/espacios-academicos/espacios-academicos-routing.module.ts
- src/app/pages/espacios-academicos/espacios-academicos.component.html
- src/app/pages/espacios-academicos/espacios-academicos.component.scss
- src/app/pages/espacios-academicos/espacios-academicos.component.ts
- src/app/pages/espacios-academicos/espacios-academicos.module.ts
- src/app/pages/espacios-academicos/preinscripcion-espacios-academicos/preinscripcion-espacios-academicos.component.html
- src/app/pages/espacios-academicos/preinscripcion-espacios-academicos/preinscripcion-espacios-academicos.component.spec.ts
- src/app/pages/espacios-academicos/preinscripcion-espacios-academicos/preinscripcion-espacios-academicos.component.ts
- src/app/pages/pages-menu.ts
- src/app/pages/pages-routing.module.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
feat: Se realiza maquetación para preinscripción de espacios académicos. #500
> Maquetación para preinscripción de asignaturas

- src/app/pages/admision/criterio_admision/criterio_admision.component.html
- src/app/pages/admision/criterio_admision/criterio_admision.component.ts
- src/app/pages/admision/listado_aspirantes/listado_aspirante.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
fix: ajuste lista aspirantes, ajuste subcriterios
> fix: ajuste lista aspirantes, ajuste subcriterios

- src/app/pages/admision/criterio_admision/criterio_admision.component.ts
fix: ajuste carga periodo criterios de admision posgrado
> fix: ajuste carga periodo criterios de admision posgrado

- src/app/pages/inscripcion/inscripcion_general/inscripcion_general.component.ts
fix: ajuste de porcentaje del tab de informacion basica #499
> fix: ajuste de porcentaje del tab de informacion basica #499

- src/app/pages/admision/actualizacion_estado/actualizacion_estado.component.scss
- src/app/pages/admision/administrador-criterios/administrador-criterios.component.scss
- src/app/pages/admision/dialogo-criterios/dialogo-criterios.component.scss
- src/app/pages/admision/dialogo-documentos/dialogo-documentos.component.scss
- src/app/pages/admision/evaluacion-aspirantes/evaluacion-aspirantes.component.scss
- src/app/pages/admision/evaluacion-documentos-inscritos/evaluacion-documentos-inscritos.component.scss
- src/app/pages/admision/listado_aspirantes/listado_aspirante.component.scss
- src/app/pages/calendario-academico/calendario-academico.component.scss
- src/app/pages/practicas-academicas/practicas-academicas.component.scss
- src/app/pages/solicitudes/solicitudes.component.scss
fix: se eliminan mas estilos repetidos. #499
> Estilos repetidos

- .drone.yml
devops: se actualiza versión de node en drone por la mas reciente disponible. #499
> Node version

- src/app/pages/admision/criterio_admision/criterio_admision.component.ts
> fix: ajustes subcriterios

- .drone.yml
- src/app/pages/admision/criterio_admision/criterio_admision.component.ts
management: ajustes de admisión
> Ajustes de admisión

- .drone.yml
hotfix: Ajuste del step publish_s3_release y master según sugerencia de infraestructura en el archivo de pipeline
> hotfix: Ajuste del step publish_s3_release y master según sugerencia de infraestructura en el archivo de pipeline

- src/app/@core/data/models/proyecto_academico/coordinador.ts
- src/app/@core/data/models/terceros/vinculacion.ts
- src/app/pages/proyecto_academico/list-proyecto_academico/list-proyecto_academico.component.ts
- src/app/pages/proyecto_academico/modificar-proyecto_academico/modificar-proyecto_academico.component.html
- src/app/pages/proyecto_academico/modificar-proyecto_academico/modificar-proyecto_academico.component.ts
- src/app/pages/proyecto_academico/proyecto_academico.module.ts
se ajusto el servicio de carga del coordinador con el servicio de terceros_crud. #540
> fix: carga academica

- src/app/@core/_Interceptor/auth.Interceptor.ts
- src/app/pages/admision/administrador-criterios/administrador-criterios.component.html
- src/app/pages/admision/administrador-criterios/administrador-criterios.component.scss
- src/app/pages/admision/administrador-criterios/administrador-criterios.component.ts
- src/app/pages/admision/criterio_admision/criterio_admision.component.ts
- src/app/pages/admision/evaluacion-documentos-inscritos/evaluacion-documentos-inscritos.component.scss
- src/app/pages/admision/evaluacion-documentos-inscritos/evaluacion-documentos-inscritos.component.ts
- src/app/pages/calendario-academico/actividad-calendario-academico/actividad-calendario-academico.component.ts
- src/app/pages/calendario-academico/calendario-academico.component.scss
- src/app/pages/calendario-academico/def-calendario-academico/def-calendario-academico.component.html
- src/app/pages/calendario-academico/def-calendario-academico/def-calendario-academico.component.ts
- src/app/pages/calendario-academico/detalle-calendario/detalle-calendario.component.ts
- src/app/pages/calendario-academico/list-calendario-academico/list-calendario-academico.component.html
- src/app/pages/calendario-academico/list-calendario-academico/list-calendario-academico.component.ts
- src/app/pages/derechos-pecuniarios/copiar-conceptos/copiar-conceptos.component.ts
- src/app/pages/derechos-pecuniarios/definir-conceptos/definir-conceptos.component.html
- src/app/pages/derechos-pecuniarios/definir-conceptos/definir-conceptos.component.ts
- src/app/pages/pages.component.ts
- src/app/pages/periodo/crud-periodo/crud-periodo.component.ts
- src/app/pages/periodo/list-periodo/list-periodo.component.scss
- src/app/pages/periodo/list-periodo/list-periodo.component.ts
- src/app/pages/practicas-academicas/list-practicas-academicas/list-practicas-academicas.component.ts
- src/app/pages/solicitudes/list-solicitudes-estudiante/list-solicitudes-estudiante.component.html
- src/app/pages/solicitudes/list-solicitudes-estudiante/list-solicitudes-estudiante.component.ts
- src/app/pages/solicitudes/solicitudes.component.scss
- src/app/pages/tipo_inscripcion/list-tipo_inscripcion/list-tipo_inscripcion.component.ts
- src/app/pages/tipo_periodo/list-tipo_periodo/list-tipo_periodo.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
> feat: solución issue labels

- src/assets/i18n/en.json
- src/assets/i18n/es.json
hotfix: ajuste de nombre de submenu de admisiones
> hotfix: ajuste de nombre de submenu de admisiones

- src/app/pages/idiomas/view-idiomas/view-idiomas.component.html
hotfix: resumen de idioma corregido #567
> hotfix: resumen de idioma corregido #567

- src/app/@core/store/services/list.service.ts
- src/app/pages/documento_programa/list-documento_programa/list-documento_programa.component.ts
- src/app/pages/documento_programa/view-documento_programa/view-documento_programa.component.ts
- src/app/pages/info_persona/crud-info_persona/crud-info_persona.component.html
- src/app/pages/inscripcion/inscripcion_general/inscripcion_general.component.ts
- src/app/pages/propuesta_grado/crud-propuesta_grado/crud-propuesta_grado.component.html
- src/app/pages/propuesta_grado/crud-propuesta_grado/crud-propuesta_grado.component.ts
- src/app/pages/propuesta_grado/crud-propuesta_grado/form-propuesta_grado.ts
- src/app/pages/propuesta_grado/view-propuesta_grado/view-propuesta_grado.component.html
- src/app/pages/propuesta_grado/view-propuesta_grado/view-propuesta_grado.component.scss
- src/app/pages/propuesta_grado/view-propuesta_grado/view-propuesta_grado.component.ts
Ajustes en end-points y carga de porcentajes. #568
> Ajustes en end-points y carga de porcentajes. #568

- src/app/@core/store/services/list.service.ts
- src/app/pages/documento_programa/list-documento_programa/list-documento_programa.component.ts
- src/app/pages/documento_programa/view-documento_programa/view-documento_programa.component.ts
- src/app/pages/idiomas/view-idiomas/view-idiomas.component.html
- src/app/pages/info_persona/crud-info_persona/crud-info_persona.component.html
- src/app/pages/inscripcion/inscripcion_general/inscripcion_general.component.ts
- src/app/pages/propuesta_grado/crud-propuesta_grado/crud-propuesta_grado.component.html
- src/app/pages/propuesta_grado/crud-propuesta_grado/crud-propuesta_grado.component.ts
- src/app/pages/propuesta_grado/crud-propuesta_grado/form-propuesta_grado.ts
- src/app/pages/propuesta_grado/view-propuesta_grado/view-propuesta_grado.component.html
- src/app/pages/propuesta_grado/view-propuesta_grado/view-propuesta_grado.component.scss
- src/app/pages/propuesta_grado/view-propuesta_grado/view-propuesta_grado.component.ts
hotfix: Ajustes en end-points y carga de porcentajes
> hotfix: Ajustes en end-points y carga de porcentajes

- src/app/pages/info_persona/crud-info_persona/crud-info_persona.component.ts
- src/app/pages/inscripcion/crud-inscripcion_multiple/crud-inscripcion_multiple.component.ts
Ajuste de carga del modulo de inscripción. #567
> Ajuste de carga del modulo de inscripción. #567

- src/app/pages/proyecto_academico/list-proyecto_academico/list-proyecto_academico.component.html
- src/app/pages/proyecto_academico/list-proyecto_academico/list-proyecto_academico.component.scss
- src/app/pages/proyecto_academico/list-proyecto_academico/list-proyecto_academico.component.ts
- src/app/pages/proyecto_academico/list-registro_proyecto_academico/list-registro_proyecto_academico.component.html
- src/app/pages/proyecto_academico/list-registro_proyecto_academico/list-registro_proyecto_academico.component.scss
- src/app/pages/proyecto_academico/list-registro_proyecto_academico/list-registro_proyecto_academico.component.ts
- src/app/pages/proyecto_academico/proyecto_academico.component.scss
- src/app/pages/proyecto_academico/proyecto_academico.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
Ajuste de las tablas a ng2-smart-table. #561
> Ajuste de las tablas a ng2-smart-table. #561

- src/app/pages/admision/administrador-criterios/administrador-criterios.component.html
- src/app/pages/admision/asignacion_cupos/asignacion_cupos.component.html
- src/app/pages/admision/asignacion_cupos/asignacion_cupos.component.scss
- src/app/pages/admision/criterio_admision/criterio_admision.component.html
- src/app/pages/admision/criterio_admision/criterio_admision.component.scss
- src/app/pages/admision/criterio_admision/criterio_admision.component.ts
- src/app/pages/admision/evaluacion-aspirantes/evaluacion-aspirantes.component.html
- src/app/pages/admision/evaluacion-aspirantes/evaluacion-aspirantes.component.scss
- src/app/pages/admision/evaluacion-aspirantes/evaluacion-aspirantes.component.ts
- src/app/pages/admision/evaluacion-documentos-inscritos/evaluacion-documentos-inscritos.component.html
- src/app/pages/admision/evaluacion-documentos-inscritos/evaluacion-documentos-inscritos.component.scss
- src/app/pages/admision/listado_aspirantes/listado_aspirante.component.html
- src/app/pages/admision/listado_aspirantes/listado_aspirante.component.scss
- src/app/pages/asignacion_cupo/crud-asignacion_cupo/crud-asignacion_cupo.component.html
- src/app/pages/asignacion_cupo/crud-asignacion_cupo/crud-asignacion_cupo.component.ts
- src/app/pages/documento_programa/view-documento_programa/view-documento_programa.component.ts
- src/app/pages/info_caracteristica/crud-info_caracteristica/crud-info_caracteristica.component.ts
- src/app/pages/informacion_contacto/crud-informacion_contacto/crud-informacion_contacto.component.ts
- src/app/pages/inscripcion/perfil/perfil.component.ts
- src/app/pages/inscripcion/preinscripcion/preinscripcion.component.scss
- src/app/pages/inscripcion/preinscripcion/preinscripcion.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
Ajuste del modulo de admisiones.#571
> Ajuste del modulo de admisiones.#571

- src/app/@theme/components/checkbox-assistance/checkbox-assistance.component.html
- src/app/pages/admision/evaluacion-aspirantes/evaluacion-aspirantes.component.html
- src/app/pages/admision/evaluacion-aspirantes/evaluacion-aspirantes.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
Fix: Ajustes de carga de evaluación de aspirantes #571
> Fix: Ajustes de carga de evaluación de aspirantes #571

- src/app/pages/admision/evaluacion-aspirantes/evaluacion-aspirantes.component.ts
- src/app/pages/admision/listado_aspirantes/listado_aspirante.component.ts
fix: corrección de errores de carga. #571
> fix: corrección de errores de carga. #571

- src/app/pages/admision/evaluacion-documentos-inscritos/evaluacion-documentos-inscritos.component.ts
Ajuste de carga al actualizar estado de documento. #571
> Ajuste de carga al actualizar estado de documento #571

- src/app/pages/admision/criterio_admision/criterio_admision.component.ts
solución de error al guardar subcriterios en modulo de admisiones
> Fix: solución de error al guardar subcriterios en modulo de admisiones

- src/app/pages/calendario-academico/asignar-calendario-proyecto/asignar-calendario-proyecto.component.ts
Se ajustaron los proyectos de acuerdo a las relaciones de padre e hijo #562
> Se ajustaron los proyectos de acuerdo a las relaciones de padre e hijo #562

- src/app/pages/admision/criterio_admision/criterio_admision.component.ts
- src/app/pages/calendario-academico/asignar-calendario-proyecto/asignar-calendario-proyecto.component.ts
- src/app/pages/calendario-academico/calendario-proyecto/calendario-proyecto.component.ts
- src/app/pages/inscripcion/crud-inscripcion_multiple/crud-inscripcion_multiple.component.ts
Ajuste de solicitudes para proyectos hijos. #562
> Ajuste de solicitudes para proyectos hijos. #562

- src/app/pages/admision/criterio_admision/criterio_admision.component.ts
- src/app/pages/calendario-academico/asignar-calendario-proyecto/asignar-calendario-proyecto.component.ts
- src/app/pages/calendario-academico/calendario-proyecto/calendario-proyecto.component.ts
- src/app/pages/inscripcion/crud-inscripcion_multiple/crud-inscripcion_multiple.component.ts
management: Ajustes de niveles de padre e hijo programa
> management: Ajustes de niveles de padre e hijo programa

- src/app/@core/data/models/idioma/info_idioma.ts
- src/app/@core/data/models/informacion/info_caracteristica_get.ts
- src/app/pages/documento_programa/crud-documento_programa/crud-documento_programa.component.html
- src/app/pages/documento_programa/crud-documento_programa/crud-documento_programa.component.ts
- src/app/pages/documento_programa/list-documento_programa/list-documento_programa.component.html
- src/app/pages/documento_programa/list-documento_programa/list-documento_programa.component.ts
- src/app/pages/idiomas/crud-idiomas/crud-idiomas.component.ts
- src/app/pages/info_caracteristica/crud-info_caracteristica/crud-info_caracteristica.component.ts
- src/app/pages/informacion_contacto/crud-informacion_contacto/crud-informacion_contacto.component.ts
- src/app/pages/inscripcion/inscripcion_general/inscripcion_general.component.ts
- src/app/pages/produccion_academica/crud-produccion_academica/crud-produccion_academica.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
Ajuste en porcentaje de documentos, y ajustes menores en modulo de inscripciones. #619
> Ajuste en porcentaje de documentos, y ajustes menores en modulo de inscripciones. #619

- src/app/@theme/components/dinamicform/dinamicform.component.html
- src/app/@theme/components/dinamicform/dinamicform.component.ts
- src/app/pages/admision/evaluacion-aspirantes/evaluacion-aspirantes.component.ts
Solución de bug al limpiar inputs tipo file. #619
> Solución de bug al limpiar inputs tipo file. #619

- src/app/pages/admision/evaluacion-aspirantes/evaluacion-aspirantes.component.html
- src/app/pages/admision/evaluacion-aspirantes/evaluacion-aspirantes.component.ts
Ajuste de carga de los aspirantes a evaluar. #571
> Ajuste de carga de los aspirantes a evaluar. #571

- src/app/pages/info_persona/crud-info_persona/crud-info_persona.component.ts
- src/app/pages/inscripcion/crud-inscripcion_multiple/crud-inscripcion_multiple.component.ts
fix: ajuste en la generación de un nuevo recibo. #620
> fix: ajuste en la generación de un nuevo recibo. #620

- src/app/pages/experiencia_laboral/crud-experiencia_laboral/crud-experiencia_laboral.component.ts
- src/app/pages/formacion_academica/crud-formacion_academica/crud-formacion_academica.component.ts
- src/app/pages/formacion_academica/view-formacion_academica/view-formacion_academica.component.ts
- src/app/pages/inscripcion/inscripcion_general/inscripcion_general.component.ts
fix: ajuste en la busqueda de nit de empresas e instituciones #636
> fix: ajuste en la busqueda de nit de empresas e instituciones #636

- src/app/@core/data/models/documento/documento_programa.ts
- src/app/pages/documento_programa/crud-documento_programa/crud-documento_programa.component.ts
- src/app/pages/documento_programa/list-documento_programa/list-documento_programa.component.ts
- src/app/pages/documento_proyecto/select-documento-proyecto/select-documento-proyecto.component.ts
- src/app/pages/inscripcion/inscripcion_general/inscripcion_general.component.ts
fix: Corrección de errores en compilación e inscripción. #639
> fix: Corrección de errores en compilación e inscripción. #639

- src/app/pages/admision/asignar_documentos_descuentos/asignar_documentos_descuentos.component.html
- src/app/pages/documento_proyecto/list-documento-proyecto/list-documento-proyecto.component.ts
fix: variables no decalradas. #639
> fix: variables no decalradas. #639

- src/app/pages/pages.component.ts
> fix: carga de menu. #639

- src/app/pages/descuento_proyecto/crud-descuento-proyecto/crud-descuento-proyecto.component.ts
- src/app/pages/descuento_proyecto/crud-descuento-proyecto/form-descuento-proyecto.ts
- src/app/pages/descuento_proyecto/descuento-proyecto.module.ts
- src/app/pages/descuento_proyecto/list-descuento-proyecto/list-descuento-proyecto.component.ts
- src/app/pages/descuento_proyecto/select-descuento-proyecto/select-descuento-proyecto.component.html
- src/app/pages/descuento_proyecto/select-descuento-proyecto/select-descuento-proyecto.component.ts
- src/app/pages/documento_proyecto/crud-documento-proyecto/crud-documento-proyecto.component.ts
- src/app/pages/documento_proyecto/crud-documento-proyecto/form-documento-proyecto.ts
- src/app/pages/documento_proyecto/list-documento-proyecto/list-documento-proyecto.component.ts
- src/app/pages/documento_proyecto/select-documento-proyecto/select-documento-proyecto.component.html
- src/app/pages/documento_proyecto/select-documento-proyecto/select-documento-proyecto.component.ts
- src/app/pages/inscripcion/inscripcion_general/inscripcion_general.component.ts
feat: creación, modificación y des habilitación de documentos y descuentos. #646
> feat: creación, modificación y des habilitación de documentos y descuentos. #646

- src/app/pages/descuento_proyecto/crud-descuento-proyecto/crud-descuento-proyecto.component.ts
- src/app/pages/descuento_proyecto/crud-descuento-proyecto/form-descuento-proyecto.ts
- src/app/pages/descuento_proyecto/descuento-proyecto.module.ts
- src/app/pages/descuento_proyecto/list-descuento-proyecto/list-descuento-proyecto.component.ts
- src/app/pages/descuento_proyecto/select-descuento-proyecto/select-descuento-proyecto.component.html
- src/app/pages/descuento_proyecto/select-descuento-proyecto/select-descuento-proyecto.component.ts
- src/app/pages/documento_proyecto/crud-documento-proyecto/crud-documento-proyecto.component.ts
- src/app/pages/documento_proyecto/crud-documento-proyecto/form-documento-proyecto.ts
- src/app/pages/documento_proyecto/list-documento-proyecto/list-documento-proyecto.component.ts
- src/app/pages/documento_proyecto/select-documento-proyecto/select-documento-proyecto.component.html
- src/app/pages/documento_proyecto/select-documento-proyecto/select-documento-proyecto.component.ts
- src/app/pages/inscripcion/inscripcion_general/inscripcion_general.component.ts
- src/app/pages/pages.component.ts
feat: creación, modificación y des habilitación de documentos y descuentos.
> feat: creación, modificación y des habilitación de documentos y descuentos.

- src/environments/environment.dev.ts
- src/environments/environment.prod.ts
- src/environments/environment.test.ts
- src/environments/environment.ts
hotfix: ajuste de versión en la variable descuento academico
> hotfix: ajuste de versión en la variable descuento academico

- src/app/pages/descuento_proyecto/crud-descuento-proyecto/crud-descuento-proyecto.component.scss
- src/app/pages/descuento_proyecto/list-descuento-proyecto/list-descuento-proyecto.component.html
- src/app/pages/descuento_proyecto/list-descuento-proyecto/list-descuento-proyecto.component.scss
- src/app/pages/descuento_proyecto/list-descuento-proyecto/list-descuento-proyecto.component.ts
- src/app/pages/descuento_proyecto/select-descuento-proyecto/select-descuento-proyecto.component.html
- src/app/pages/descuento_proyecto/select-descuento-proyecto/select-descuento-proyecto.component.ts
- src/app/pages/documento_proyecto/crud-documento-proyecto/crud-documento-proyecto.component.scss
- src/app/pages/documento_proyecto/list-documento-proyecto/list-documento-proyecto.component.html
- src/app/pages/documento_proyecto/list-documento-proyecto/list-documento-proyecto.component.scss
- src/app/pages/documento_proyecto/list-documento-proyecto/list-documento-proyecto.component.ts
- src/app/pages/documento_proyecto/select-documento-proyecto/select-documento-proyecto.component.html
- src/app/pages/documento_proyecto/select-documento-proyecto/select-documento-proyecto.component.ts
feat: Botones de cerrar dialog y mascará de true y false para descuentos y documentos por proyecto académico. #639
> feat: Botones de cerrar dialog y mascará de true y false para descuentos y documentos por proyecto académico. #639

- src/app/pages/formacion_academica/view-formacion_academica/view-formacion_academica.component.scss
- src/app/pages/formacion_academica/view-formacion_academica/view-formacion_academica.component.ts
feat: muestra de documentos de información académica. udistrital/sga_mid#308
> feat: muestra de documentos de información academica. udistrital/sga_mid#308

- src/app/@core/data/models/derechos-pecuniarios/concepto-recibo.ts
- src/app/@core/data/models/derechos-pecuniarios/recibo_pago.ts
- src/app/pages/derechos-pecuniarios/generacion-recibos-derechos-pecuniarios/generacion-recibos-derechos-pecuniarios.component.html
- src/app/pages/derechos-pecuniarios/generacion-recibos-derechos-pecuniarios/generacion-recibos-derechos-pecuniarios.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
feat: Implementación de la generación de los recibos de pago para derechos pecuniarios. #671
> feat: Implementación de la generación de los recibos de pago para derechos pecuniarios. #671

- src/app/@core/data/models/informacion/info_caracteristica_get.ts
- src/app/@core/store/services/list.service.ts
- src/app/pages/info_caracteristica/crud-info_caracteristica/crud-info_caracteristica.component.ts
feat: ajustes para la lectura de archivo. udistrital/sga_mid#313
> feat: ajustes para la lectura de archivo. udistrital/sga_mid#313

- src/app/pages/info_caracteristica/crud-info_caracteristica/crud-info_caracteristica.component.ts
fix: Solución al guardado de documentos. udistrital/sga_mid#313
> fix: Solución al guardado de documentos. udistrital/sga_mid#313

- src/app/pages/admision/evaluacion-aspirantes/evaluacion-aspirantes.component.ts
- src/app/pages/admision/evaluacion-documentos-inscritos/evaluacion-documentos-inscritos.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
fix: al evaluar aspirantes, no capturaba cuando no había aspirantes por evaluar
> fix: al evaluar aspirantes, no capturaba cuando no había aspirantes por evaluar

- src/app/pages/experiencia_laboral/crud-experiencia_laboral/crud-experiencia_laboral.component.ts
- src/app/pages/experiencia_laboral/list-experiencia_laboral/list-experiencia_laboral.component.html
- src/app/pages/experiencia_laboral/list-experiencia_laboral/list-experiencia_laboral.component.ts
- src/app/pages/formacion_academica/crud-formacion_academica/crud-formacion_academica.component.ts
- src/app/pages/formacion_academica/list-formacion_academica/list-formacion_academica.component.html
- src/app/pages/formacion_academica/list-formacion_academica/list-formacion_academica.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
feat: Ajustes en modulo de experiencia laboral y formación académica. #701
> feat: Ajustes en modulo de experiencia laboral y formación académica. #701

- src/app/pages/proyecto_academico/list-proyecto_academico/list-proyecto_academico.component.html
fix: correccion de error de compilación. #729
> fix: correccion de error de compilación. #729

- src/app/pages/proyecto_academico/crud-proyecto_academico/crud-proyecto_academico.component.html
fix: ajustes de errores de compilación. #729
> fix: ajustes de errores de compilación. #729

- src/app/pages/proyecto_academico/crud-proyecto_academico/crud-proyecto_academico.component.html
- src/app/pages/proyecto_academico/list-proyecto_academico/list-proyecto_academico.component.html
> hotfix: ajuste de compilación 

- src/app/pages/calendario-academico/calendario-proyecto/calendario-proyecto.component.html
- src/app/pages/calendario-academico/list-calendario-academico/list-calendario-academico.component.html
- src/app/pages/proyecto_academico/crud-proyecto_academico/crud-proyecto_academico.component.html
- src/app/pages/proyecto_academico/list-proyecto_academico/list-proyecto_academico.component.html
- src/app/pages/proyecto_academico/proyecto_academico.component.scss
- src/app/pages/proyecto_academico/proyecto_academico.module.ts
fix: corrección en los iconos de mat-icons. #729
> fix: corrección en los iconos de mat-icons. #729

- src/app/pages/admision/asignar_documentos_descuentos/asignar_documentos_descuentos.component.html
feat: configuración de roles para modulo de descuentos. #731
> feat: configuración de roles para modulo de descuentos. #731

- src/app/@theme/styles/styles.scss
- src/app/pages/admision/asignar_documentos_descuentos/asignar_documentos_descuentos.component.html
- src/app/pages/inscripcion/inscripcion_general/inscripcion_general.component.html
- src/app/pages/propuesta_grado/crud-propuesta_grado/crud-propuesta_grado.component.ts
- src/assets/i18n/es.json
management: desarrollo de la funcionalidad de no aplica en trabajo de grado
> management: desarrollo de la funcionalidad de no aplica en trabajo de grado 

- src/app/pages/info_caracteristica/crud-info_caracteristica/crud-info_caracteristica.component.ts
fix: Ajuste de carga de documentos en componente de información característica. #744
> fix: Ajuste de carga de documentos en componente de información característica. #744

- src/app/pages/info_caracteristica/crud-info_caracteristica/crud-info_caracteristica.component.ts
- src/app/pages/inscripcion/inscripcion_general/inscripcion_general.component.ts
fix: ajuste en carga de componente. #744
> fix: ajuste en carga de componente. #744

- src/app/pages/info_caracteristica/crud-info_caracteristica/crud-info_caracteristica.component.ts
- src/app/pages/inscripcion/inscripcion_general/inscripcion_general.component.ts
hotfix: ajuste en carga de componente.
> hotfix: ajuste en carga de componente.

- src/app/pages/info_caracteristica/crud-info_caracteristica/crud-info_caracteristica.component.ts
- src/app/pages/info_caracteristica/crud-info_caracteristica_pregrado/crud-info_caracteristica_pregrado.component.ts
- src/app/pages/informacion_contacto/crud-informacion_contacto/crud-informacion_contacto.component.ts
feat: ajustes de cargas de información de contacto. #767
> feat: ajustes de cargas de información de contacto. #767

- src/app/pages/info_caracteristica/crud-info_caracteristica/crud-info_caracteristica.component.ts
- src/app/pages/informacion_contacto/crud-informacion_contacto/crud-informacion_contacto.component.ts
- src/app/pages/inscripcion/inscripcion_general/inscripcion_general.component.html
fix: ajuste de porcentaje. #767
> fix: ajuste de porcentaje. #767

- src/app/pages/info_caracteristica/crud-info_caracteristica/crud-info_caracteristica.component.ts
- src/app/pages/info_caracteristica/crud-info_caracteristica_pregrado/crud-info_caracteristica_pregrado.component.ts
- src/app/pages/informacion_contacto/crud-informacion_contacto/crud-informacion_contacto.component.ts
- src/app/pages/inscripcion/inscripcion_general/inscripcion_general.component.html
> hotfix: ajuste de porcentaje. 

- src/app/@core/data/models/practicas_academicas/solicitud_practica_academica.ts
- src/app/@core/data/practicas_academicas.service.ts
- src/app/pages/admision/actualizacion_estado/actualizacion_estado.component.ts
- src/app/pages/practicas-academicas/detalle-practica-academica/detalle-practica-academica.component.html
- src/app/pages/practicas-academicas/detalle-practica-academica/detalle-practica-academica.component.ts
- src/app/pages/practicas-academicas/list-practicas-academicas/list-practicas-academicas.component.html
- src/app/pages/practicas-academicas/list-practicas-academicas/list-practicas-academicas.component.ts
- src/app/pages/practicas-academicas/nueva-solicitud/nueva-solicitud.component.html
- src/app/pages/practicas-academicas/nueva-solicitud/nueva-solicitud.component.ts
- src/app/pages/practicas-academicas/practicas-academicas.module.ts
- src/app/pages/practicas-academicas/solicitante-practica/solicitante-practica.component.html
- src/app/pages/practicas-academicas/solicitante-practica/solicitante-practica.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
feat: Implementación de búsqueda de estados. #768
> feat: Implementación de búsqueda de estados. #768

- src/app/pages/info_caracteristica/crud-info_caracteristica/crud-info_caracteristica.component.ts
feat: Corrección en la carga del porcentaje. #767
> feat: Corrección en la carga del porcentaje. #767

- src/app/@core/data/practicas_academicas.service.ts
- src/app/@theme/components/download-file-nuxeo/download-file-nuxeo.component.html
- src/app/pages/practicas-academicas/detalle-practica-academica/detalle-practica-academica.component.html
- src/app/pages/practicas-academicas/detalle-practica-academica/detalle-practica-academica.component.ts
- src/app/pages/practicas-academicas/form-solicitud-practica.ts
- src/app/pages/practicas-academicas/list-practicas-academicas/list-practicas-academicas.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
feat: cambio de estado de las practicas a académicas. #775
> feat: cambio de estado de las practicas a académicas. #775

- src/app/managers/popUpManager.ts
- src/app/pages/idiomas/list-idiomas/list-idiomas.component.ts
- src/app/pages/inscripcion/inscripcion_general/inscripcion_general.component.ts
feat: Ajustes en porcentaje de inscripción y idiomas. #819
> feat: Ajustes en porcentaje de inscripción y idiomas. #819

- src/app/@core/store/services/list.service.ts
- src/app/@theme/components/dinamicform/dinamicform.component.ts
- src/app/pages/descuento_academico/crud-descuento_academico/crud-descuento_academico.component.html
- src/app/pages/descuento_academico/crud-descuento_academico/crud-descuento_academico.component.ts
- src/app/pages/descuento_academico/list-descuento_academico/list-descuento_academico.component.ts
- src/app/pages/documento_programa/list-documento_programa/list-documento_programa.component.ts
- src/app/pages/info_caracteristica/crud-info_caracteristica/crud-info_caracteristica.component.ts
- src/app/pages/informacion_contacto/crud-informacion_contacto/crud-informacion_contacto.component.ts
- src/app/pages/inscripcion/inscripcion_general/inscripcion_general.component.ts
- src/assets/i18n/es.json
feat: ajustes en modulo de preinscripción. #819
> feat: ajustes en modulo de preinscripción. #819

- src/app/pages/informacion_contacto/crud-informacion_contacto/crud-informacion_contacto.component.ts
- src/app/pages/informacion_contacto/view-informacion_contacto/view-informacion_contacto.component.ts
fix: carga de información de contacto. #819
> fix: carga de información de contacto. #819

- src/app/@core/data/practicas_academicas.service.ts
- src/app/@core/store/services/list.service.ts
- src/app/@core/utils/pivot_document.service.ts
- src/app/pages/admision/evaluacion-documentos-inscritos/evaluacion-documentos-inscritos.component.ts
- src/app/pages/descuento_academico/view-descuento_academico/view-descuento_academico.component.ts
- src/app/pages/documento_programa/view-documento_programa/view-documento_programa.component.scss
- src/app/pages/documento_programa/view-documento_programa/view-documento_programa.component.ts
- src/app/pages/experiencia_laboral/view-experiencia_laboral/view-experiencia_laboral.component.ts
- src/app/pages/formacion_academica/view-formacion_academica/view-formacion_academica.component.ts
- src/app/pages/inscripcion/perfil/perfil.component.html
- src/app/pages/inscripcion/perfil/perfil.component.ts
- src/app/pages/practicas-academicas/detalle-practica-academica/detalle-practica-academica.component.ts
- src/app/pages/practicas-academicas/list-practicas-academicas/list-practicas-academicas.component.ts
- src/app/pages/propuesta_grado/crud-propuesta_grado/crud-propuesta_grado.component.ts
- src/app/pages/propuesta_grado/view-propuesta_grado/view-propuesta_grado.component.ts
- src/app/pages/solicitudes/actualizacion-datos/actualizacion-datos.component.ts
feat: ajustes en descuentos y practicas a académicas. #819
> feat: ajustes en descuentos y practicas a académicas.

- src/app/pages/propuesta_grado/crud-propuesta_grado/crud-propuesta_grado.component.ts
fix: ajuste en propuesta de grado. #819
> fix: ajuste en propuesta de grado. #819

- src/app/pages/practicas-academicas/detalle-practica-academica/detalle-practica-academica.component.html
- src/app/pages/practicas-academicas/detalle-practica-academica/detalle-practica-academica.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
feat: funcionalidad para el envió de invitaciones de prácticas académias. #776
> feat: funcionalidad para el envió de invitaciones de prácticas académias. #776

- src/app/pages/practicas-academicas/detalle-practica-academica/detalle-practica-academica.component.html
- src/app/pages/practicas-academicas/detalle-practica-academica/detalle-practica-academica.component.ts
- src/app/pages/propuesta_grado/crud-propuesta_grado/crud-propuesta_grado.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
management: Integración de funcionalidad de envió de invitaciones para prácticas académicas. #776
> management: Integración de funcionalidad de envió de invitaciones para prácticas académicas. #776 

- src/app/@theme/components/new-tercero/new-tercero.component.ts
- src/app/pages/experiencia_laboral/crud-experiencia_laboral/crud-experiencia_laboral.component.ts
- src/app/pages/formacion_academica/crud-formacion_academica/crud-formacion_academica.component.ts
fix: formato de nit para empresas e instituciones
> fix: formato de nit para empresas e instituciones

- src/app/@core/data/practicas_academicas.service.ts
- src/app/pages/practicas-academicas/detalle-practica-academica/detalle-practica-academica.component.ts
- src/app/pages/practicas-academicas/list-practicas-academicas/list-practicas-academicas.component.ts
feat: ajuste para filtrado de prácticas académicas. #777
> feat: ajuste para filtrado de prácticas académicas. #777

- src/app/pages/practicas-academicas/detalle-practica-academica/detalle-practica-academica.component.html
- src/app/pages/practicas-academicas/detalle-practica-academica/detalle-practica-academica.component.ts
- src/app/pages/practicas-academicas/list-practicas-academicas/list-practicas-academicas.component.ts
- src/app/pages/practicas-academicas/nueva-solicitud/nueva-solicitud.component.html
- src/app/pages/practicas-academicas/nueva-solicitud/nueva-solicitud.component.ts
- src/app/pages/practicas-academicas/solicitante-practica/solicitante-practica.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
feat: ajustes de refactor para prácticas académicas. #820
> feat: ajustes de refactor para prácticas académicas. #820

- src/app/@theme/components/button-payment/button-payment.component.scss
- src/app/@theme/components/customize-button/customize-button.component.html
- src/app/@theme/components/customize-button/customize-button.component.scss
- src/app/@theme/components/link-download-nuxeo/link-download-nuxeo.component.html
- src/app/@theme/components/link-download/link-download.component.scss
- src/app/pages/derechos-pecuniarios/definir-conceptos/definir-conceptos.component.ts
- src/app/pages/derechos-pecuniarios/generacion-recibos-derechos-pecuniarios/generacion-recibos-derechos-pecuniarios.component.html
- src/app/pages/derechos-pecuniarios/generacion-recibos-derechos-pecuniarios/generacion-recibos-derechos-pecuniarios.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
feat: desarrollo de funcionalidades para la tabla de derechos pecuniarios solicitados. #810
> feat: desarrollo de funcionalidades para la tabla de derechos pecuniarios solicitados. #810

- src/app/@core/utils/new_nuxeo.service.ts
- src/app/@theme/components/button-payment/button-payment.component.scss
- src/app/pages/admision/dialogo-documentos/dialogo-documentos.component.html
- src/app/pages/admision/evaluacion-documentos-inscritos/evaluacion-documentos-inscritos.component.html
- src/app/pages/derechos-pecuniarios/consultar-solicitudes/consultar-solicitudes.component.ts
- src/app/pages/derechos-pecuniarios/consultar-solicitudes/form-solicitud.ts
- src/app/pages/derechos-pecuniarios/derechos-pecuniarios.module.ts
- src/app/pages/derechos-pecuniarios/generacion-recibos-derechos-pecuniarios/generacion-recibos-derechos-pecuniarios.component.ts
- src/app/pages/descuento_academico/view-descuento_academico/view-descuento_academico.component.html
- src/app/pages/descuento_academico/view-descuento_academico/view-descuento_academico.component.ts
- src/app/pages/documento_programa/view-documento_programa/view-documento_programa.component.ts
- src/app/pages/experiencia_laboral/view-experiencia_laboral/view-experiencia_laboral.component.ts
- src/app/pages/formacion_academica/view-formacion_academica/view-formacion_academica.component.ts
- src/app/pages/inscripcion/perfil/perfil.component.html
- src/app/pages/inscripcion/perfil/perfil.component.ts
- src/app/pages/propuesta_grado/view-propuesta_grado/view-propuesta_grado.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
feat: respuesta de solicitudes de derechos pecuniarios y ajustes menores. #816
> feat: respuesta de solicitudes de derechos pecuniarios y ajustes menores. #816

- src/app/@core/utils/pivot_document.service.ts
- src/app/@theme/components/dinamicform/dinamicform.component.ts
- src/app/@theme/components/download-file-nuxeo/download-file-nuxeo.component.ts
- src/app/pages/admision/dialogo-documentos/dialogo-documentos.component.html
- src/app/pages/admision/dialogo-documentos/dialogo-documentos.component.ts
- src/app/pages/derechos-pecuniarios/consultar-solicitudes/form-solicitud.ts
- src/app/pages/derechos-pecuniarios/generacion-recibos-derechos-pecuniarios/generacion-recibos-derechos-pecuniarios.component.ts
fix: ajustes en componente de documentos .#817
> fix: ajustes en componente de documentos .#817

- src/app/@theme/components/dinamicform/dinamicform.component.html
- src/app/pages/inscripcion/forms-transferencia.ts
- src/app/pages/inscripcion/solicitud-transferencia/solicitud-transferencia.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
feat: creación de solicitudes de transferencia y reintegro. #861
> feat: creación de solicitudes de transferencia y reintegro. #861

- src/app/pages/practicas-academicas/detalle-practica-academica/detalle-practica-academica.component.html
- src/app/pages/practicas-academicas/detalle-practica-academica/detalle-practica-academica.component.ts
- src/app/pages/practicas-academicas/list-practicas-academicas/list-practicas-academicas.component.html
- src/app/pages/practicas-academicas/list-practicas-academicas/list-practicas-academicas.component.ts
- src/app/pages/practicas-academicas/nueva-solicitud/nueva-solicitud.component.html
- src/app/pages/practicas-academicas/nueva-solicitud/nueva-solicitud.component.ts
- src/app/pages/practicas-academicas/practicas-academicas.component.scss
- src/assets/i18n/en.json
- src/assets/i18n/es.json
fix: ajustes en modulo de practicas académicas. #898
> fix: ajustes en modulo de practicas académicas. #898

- src/app/@theme/components/dinamicform/dinamicform.component.ts
feat: Ajuste de componentes requeridos para practicas académicas. #898
> feat: Ajuste de componentes requeridos para practicas académicas. #898

- src/app/@theme/components/index.ts
- src/app/@theme/components/render-data/render-data.component.html
- src/app/@theme/components/render-data/render-data.component.scss
- src/app/@theme/components/render-data/render-data.component.spec.ts
- src/app/@theme/components/render-data/render-data.component.ts
- src/app/@theme/theme.module.ts
- src/app/pages/asignaturas/asignaturas.component.ts
- src/app/pages/asignaturas/asignaturas.module.ts
- src/app/pages/asignaturas/asignaturas.routing.module.ts
- src/app/pages/asignaturas/notas-parciales/notas-parciales.component.html
- src/app/pages/asignaturas/notas-parciales/notas-parciales.component.scss
- src/app/pages/asignaturas/notas-parciales/notas-parciales.component.spec.ts
- src/app/pages/asignaturas/notas-parciales/notas-parciales.component.ts
- src/app/pages/pages-routing.module.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
Desarrollo de componente notas parciales para rol Estudiante, se crea modulo asignaturas para alojar el componente.
Se crea componente render-data para visualización de Object notas en smart-table, se construyen las rutas pertinentes y se añade traducción en-es.
MENU
--Asignaturas
{{ 'MENU.asignaturas.asignaturas' | translate }}
path: /asignaturas
----Notas parciales
{{ 'MENU.asignaturas.notas_parciales' | translate }}
path: /asignaturas/notas-parciales
http://localhost:4200/#/pages/asignaturas/notas-parciales
> feat: Desarrollo componente Notas Parciales

- src/app/@theme/components/dinamicform/dinamicform.component.ts
- src/app/@theme/components/index.ts
- src/app/@theme/components/render-data/render-data.component.html
- src/app/@theme/components/render-data/render-data.component.scss
- src/app/@theme/components/render-data/render-data.component.spec.ts
- src/app/@theme/components/render-data/render-data.component.ts
- src/app/@theme/theme.module.ts
- src/app/pages/asignaturas/asignaturas.component.ts
- src/app/pages/asignaturas/asignaturas.module.ts
- src/app/pages/asignaturas/asignaturas.routing.module.ts
- src/app/pages/asignaturas/notas-parciales/notas-parciales.component.html
- src/app/pages/asignaturas/notas-parciales/notas-parciales.component.scss
- src/app/pages/asignaturas/notas-parciales/notas-parciales.component.spec.ts
- src/app/pages/asignaturas/notas-parciales/notas-parciales.component.ts
- src/app/pages/pages-routing.module.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
mangenet: Desarrollo componente Notas Parciales
> mangenet: Desarrollo componente Notas Parciales

- src/app/pages/derechos-pecuniarios/consultar-solicitudes/consultar-solicitudes.component.ts
- src/app/pages/inscripcion/forms-transferencia.ts
- src/app/pages/inscripcion/solicitud-transferencia/solicitud-transferencia.component.html
- src/app/pages/inscripcion/solicitud-transferencia/solicitud-transferencia.component.ts
- src/app/pages/inscripcion/transferencia/transferencia.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
feat: Carga de datos para vista de coordinador en transferencias y reingresos. #862
> feat: Carga de datos para vista de coordinador en transferencias y reingresos. #862

- src/app/pages/inscripcion/dialogo-documentos-transferencias/dialogo-documentos-transferencias.component.html
- src/app/pages/inscripcion/dialogo-documentos-transferencias/dialogo-documentos-transferencias.component.scss
- src/app/pages/inscripcion/dialogo-documentos-transferencias/dialogo-documentos-transferencias.component.spec.ts
- src/app/pages/inscripcion/dialogo-documentos-transferencias/dialogo-documentos-transferencias.component.ts
- src/app/pages/inscripcion/inscripcion-routing.module.ts
- src/app/pages/inscripcion/inscripcion.module.ts
- src/app/pages/inscripcion/solicitud-transferencia/solicitud-transferencia.component.html
- src/app/pages/inscripcion/solicitud-transferencia/solicitud-transferencia.component.ts
- src/app/pages/inscripcion/transferencia/transferencia.component.ts
- src/app/pages/practicas-academicas/detalle-practica-academica/detalle-practica-academica.component.html
feat: Integración de la respuesta y componente de respuesta de transferencia. #863
> feat: Integración de la respuesta y componente de respuesta de transferencia. #863

- src/app/pages/proyecto_academico/modificar-proyecto_academico/modificar-proyecto_academico.component.html
- src/app/pages/solicitudes/list-solicitudes-estudiante/list-solicitudes-estudiante.component.ts
fix: ajuste para despliegue. #917
> fix: ajuste para despliegue. #917

- src/app/pages/calendario-academico/def-calendario-academico/def-calendario-academico.component.ts
- src/app/pages/calendario-academico/detalle-calendario/detalle-calendario.component.ts
- src/app/pages/calendario-academico/list-calendario-academico/list-calendario-academico.component.ts
- src/app/pages/derechos-pecuniarios/generacion-recibos-derechos-pecuniarios/generacion-recibos-derechos-pecuniarios.component.html
- src/app/pages/derechos-pecuniarios/generacion-recibos-derechos-pecuniarios/generacion-recibos-derechos-pecuniarios.component.ts
- src/app/pages/inscripcion/crud-inscripcion_multiple/crud-inscripcion_multiple.component.ts
- src/app/pages/inscripcion/forms-transferencia.ts
- src/app/pages/inscripcion/inscripcion_general/inscripcion_general.component.ts
- src/app/pages/inscripcion/solicitud-transferencia/solicitud-transferencia.component.ts
- src/app/pages/registro_notas/definicion-cortes/definicion-cortes.component.ts
- src/app/pages/registro_notas/list-notas/list-notas.component.ts
fix: Ajustes en calendario y errores en practicas académicas y transferencias. #913
> fix: Ajustes en calendario y errores en practicas académicas y transferencias. #913

- src/app/pages/admision/asignacion_cupos/asignacion_cupos.component.ts
- src/app/pages/admision/asignar_documentos_descuentos/asignar_documentos_descuentos.component.ts
- src/app/pages/admision/criterio_admision/criterio_admision.component.ts
- src/app/pages/admision/evaluacion-aspirantes/evaluacion-aspirantes.component.scss
- src/app/pages/admision/evaluacion-aspirantes/evaluacion-aspirantes.component.ts
- src/app/pages/admision/listado_aspirantes/listado_aspirante.component.ts
- src/app/pages/documento_proyecto/select-documento-proyecto/select-documento-proyecto.component.html
- src/app/pages/documento_proyecto/select-documento-proyecto/select-documento-proyecto.component.ts
- src/app/pages/info_persona/crud-info_persona/crud-info_persona.component.ts
feat: correcciones para el calculo del porcentaje de criterios. #911
> feat: correcciones para el calculo del porcentaje de criterios. #911

- src/app/pages/admision/criterio_admision/criterio_admision.component.ts
- src/app/pages/asignacion_cupo/crud-asignacion_cupo/crud-asignacion_cupo.component.ts
- src/app/pages/inscripcion/crud-inscripcion_multiple/crud-inscripcion_multiple.component.ts
fix: Ajustes para respuesta de admision/postcupo. #911
> fix: Ajustes para respuesta de admision/postcupo. #911

- src/app/pages/asignacion_cupo/crud-asignacion_cupo/crud-asignacion_cupo.component.ts
fix: error en mensaje post. #911
> fix: error en mensaje post. #911

- src/app/pages/derechos-pecuniarios/consultar-conceptos/consultar-conceptos.component.ts
- src/app/pages/derechos-pecuniarios/consultar-solicitudes/consultar-solicitudes.component.ts
- src/app/pages/derechos-pecuniarios/copiar-conceptos/copiar-conceptos.component.ts
- src/app/pages/derechos-pecuniarios/definir-conceptos/definir-conceptos.component.ts
- src/app/pages/derechos-pecuniarios/generacion-recibos-derechos-pecuniarios/generacion-recibos-derechos-pecuniarios.component.ts
fix: ajustes de respuestas de derechos pecuniarios. #914
> fix: ajustes de respuestas de derechos pecuniarios. #914

- src/app/pages/inscripcion/solicitud-transferencia/solicitud-transferencia.component.ts
fix: error de búsqueda de estado de transferencias. #864
> fix: error de búsqueda de estado de transferencias. #864

- src/app/pages/info_caracteristica/crud-info_caracteristica_pregrado/crud-info_caracteristica_pregrado.component.ts
- src/app/pages/inscripcion/solicitud-transferencia/solicitud-transferencia.component.html
- src/app/pages/inscripcion/transferencia/transferencia.component.html
- src/app/pages/inscripcion/transferencia/transferencia.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
fix: errores en transferencia y reingreso #864
> fix: errores en transferencia y reingreso #864

- src/app/pages/info_caracteristica/crud-info_caracteristica_pregrado/crud-info_caracteristica_pregrado.component.ts
- src/app/pages/info_caracteristica/crud-info_caracteristica_pregrado/form-info_caracteristica_pregrado.ts
fix: Arreglos en la información básica al momento de la inscripción. #864
> fix: Arreglos en la información básica al momento de la inscripción. #864

- src/app/@core/data/models/calendario-academico/proceso.ts
- src/app/pages/calendario-academico/administracion-calendario/administracion-calendario.component.html
- src/app/pages/calendario-academico/administracion-calendario/administracion-calendario.component.spec.ts
- src/app/pages/calendario-academico/administracion-calendario/administracion-calendario.component.ts
- src/app/pages/calendario-academico/calendario-academico-routing.module.ts
- src/app/pages/calendario-academico/calendario-academico.component.scss
- src/app/pages/calendario-academico/calendario-academico.module.ts
- src/app/pages/calendario-academico/def-calendario-academico/def-calendario-academico.component.html
- src/app/pages/calendario-academico/def-calendario-academico/def-calendario-academico.component.ts
- src/app/pages/calendario-academico/detalle-calendario/detalle-calendario.component.ts
- src/app/pages/calendario-academico/edicion-actividades-programas/edicion-actividades-programas.component.html
- src/app/pages/calendario-academico/edicion-actividades-programas/edicion-actividades-programas.component.scss
- src/app/pages/calendario-academico/edicion-actividades-programas/edicion-actividades-programas.component.spec.ts
- src/app/pages/calendario-academico/edicion-actividades-programas/edicion-actividades-programas.component.ts
- src/app/pages/inscripcion/inscripcion_general/inscripcion_general.component.html
- src/app/pages/registro_notas/crud-notas/crud-notas.component.html
- src/app/pages/registro_notas/crud-notas/crud-notas.component.scss
- src/assets/i18n/en.json
- src/assets/i18n/es.json
Rol Vicerrectoría (Actividades): En tabla de actividades se añade opción de habilitación por programas para que estos puedan cambiar fechas de actividades.
En la misma tabla se añade opción de visualización para listar los programas que han configurado fechas especiales.
Rol Vicerrectoría (Extensión): Se añade pestaña |Extensión Calendario| junto a definición de calendario académico; la estructura de esta pestaña es similar a la de definición, solo que aquí se selecciona por programa académico.
Rol Programa: Creación de componente administración-calendario para visualización y ajuste de las fechas de actividades en caso de ser habilitados por parte de Vicerrectoría.
Se maneja componente edicion-actividades-programa embebido como modal para la visualización de detalles de proceso y edición …
> feat: for issue #995, Ajustes componentes módulo calendario.

- src/app/pages/inscripcion/crud-inscripcion_multiple/crud-inscripcion_multiple.component.ts
> fix: ajuste de consulta para tener en cuenta el ultimo periodo vigente

- src/app/pages/inscripcion/crud-inscripcion_multiple/crud-inscripcion_multiple.component.html
- src/app/pages/inscripcion/crud-inscripcion_multiple/crud-inscripcion_multiple.component.ts
hotfix: ajuste de lista de recibos de inscripcion.
> hotfix: ajuste de lista de recibos de inscripcion.

- src/app/pages/produccion_academica/crud-produccion_academica/crud-produccion_academica.component.html
- src/app/pages/produccion_academica/crud-produccion_academica/crud-produccion_academica.component.ts
- src/environments/environment.ts
Ya no se traen todos los terceros, se hace filtro busqueda por nombre y se lista el resultado de la busqueda en un autocomplete.
> fix: Cambio de select por autocomplete en seleccion de autor por tercero

- src/app/pages/descuento_academico/list-descuento_academico/list-descuento_academico.component.ts
- src/app/pages/documento_programa/list-documento_programa/list-documento_programa.component.ts
- src/app/pages/info_caracteristica/crud-info_caracteristica/crud-info_caracteristica.component.ts
- src/app/pages/inscripcion/crud-inscripcion_multiple/crud-inscripcion_multiple.component.ts
Ajuste para guardado de informacion básica por primera vez.
Ajuste de porcentaje diligenciado en documentos solicitados.
Captura error en tabla de descuentos, evita colapso de tabla.
Ajuste menor de listra de recibos cuando hay un null.
> fix: for issue #1016 Ajustes módulo inscripcion prod

- src/app/pages/inscripcion/inscripcion_general/inscripcion_general.component.ts
- Adicionalmente se quita filtro que remueve la opcion No aplica en el listado de énfasis.
> fix: #1029 Validación Enfasis en botón Inscripción.

- src/app/@core/utils/new_nuxeo.service.ts
- src/app/pages/admision/dialogo-documentos/dialogo-documentos.component.html
- src/app/pages/admision/dialogo-documentos/dialogo-documentos.component.ts
- src/app/pages/admision/evaluacion-documentos-inscritos/evaluacion-documentos-inscritos.component.ts
- src/app/pages/documento_programa/list-documento_programa/list-documento_programa.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
hotfix: Ajuste relacion nombre - documento en listado de documentos.
> hotfix: Ajuste relacion nombre - documento en listado de documentos.

- src/app/pages/info_caracteristica/view-info_caracteristica/view-info_caracteristica.component.ts
- src/app/pages/info_persona/view-info-persona/view-info-persona.component.html
- src/app/pages/info_persona/view-info-persona/view-info-persona.component.scss
- src/app/pages/info_persona/view-info-persona/view-info-persona.component.ts
- src/app/pages/inscripcion/perfil/perfil.component.html
Se modifica componente de vista de información básica para incluir si presenta, lista de documentos de población y discapacidad.
> feat: añadido revisión docs info caraterística en Detalle inscripcion

- src/app/pages/admision/listado_aspirantes/listado_aspirante.component.ts
Se cambia el flujo para tener en cuenta si ya cuenta con énfasis o no.
> fix: Ajuste listado aspirantes cuando no hay enfasis

- src/app/pages/admision/listado_aspirantes/listado_aspirante.component.ts
Cambio de TerceroId por número de documento de tercero.
> fix: Añadido numero documento a lista aspirantes

- src/app/pages/admision/listado_aspirantes/listado_aspirante.component.ts
hotfix: Añadido numero documento a lista aspirantes
> hotfix: Añadido numero documento a lista aspirantes

- src/app/@core/data/users.service.ts
> fix: Añadido validación activo consulta tercero

- src/app/@core/data/users.service.ts
- src/app/pages/admision/listado_aspirantes/listado_aspirante.component.ts
hotfix: Añadido validación activo consulta tercero
> hotfix: Añadido validación activo consulta tercero

- src/app/pages/admision/listado_aspirantes/listado_aspirante.component.ts
Ajuste en consulta para retornar únicamente las inscripciones activas.
> fix: consulta únicamente inscripciones activas

- src/app/@core/data/users.service.ts
- src/app/pages/admision/listado_aspirantes/listado_aspirante.component.ts
hotfix: consulta únicamente inscripciones activas
> hotfix: consulta únicamente inscripciones activas

- src/app/pages/admision/listado_aspirantes/listado_aspirante.component.ts
- src/app/pages/experiencia_laboral/crud-experiencia_laboral/crud-experiencia_laboral.component.ts
- src/app/pages/formacion_academica/crud-formacion_academica/crud-formacion_academica.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
hotfix: Validacion vacio campo NIT
> hotfix: Validacion vacio campo NIT

- src/app/pages/admision/listado_aspirantes/listado_aspirante.component.ts
Se ajusta la consulta para traer todos los aspirantes.
> fix: Ajuste líminte consulta aspirantes

- src/app/pages/admision/evaluacion-documentos-inscritos/evaluacion-documentos-inscritos.component.ts
hotfix:Ajuste de campo activo en revisión de documentos
> hotfix:Ajuste de campo activo en revisión de documentos

- src/app/pages/informacion_contacto/crud-informacion_contacto/crud-informacion_contacto.component.ts
- Manejo de Id indefinido si info_complementaria no existe
> fix: ajuste data put info_contacto

- src/app/pages/admision/admision-routing.module.ts
- src/app/pages/admision/admision.module.ts
- src/app/pages/admision/def_suite_inscrip_programa/def-suite-inscrip-programa.component.html
- src/app/pages/admision/def_suite_inscrip_programa/def-suite-inscrip-programa.component.scss
- src/app/pages/admision/def_suite_inscrip_programa/def-suite-inscrip-programa.component.spec.ts
- src/app/pages/admision/def_suite_inscrip_programa/def-suite-inscrip-programa.component.ts
- src/app/pages/admision/def_suite_inscrip_programa/def_tags_por_programa.ts
- src/app/pages/informacion_contacto/crud-informacion_contacto/crud-informacion_contacto.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
management: Creación componente & funcionalidad Suite para programas
> management: Creación componente & funcionalidad Suite para programas

- src/app/pages/info_persona/crud-info_persona/crud-info_persona.component.ts
- Ajuste nombre de variable por cambio involuntario
> hotfix: corrección nombre variable

- src/app/pages/experiencia_laboral/crud-experiencia_laboral/form-experiencia_laboral.ts
- src/app/pages/formacion_academica/crud-formacion_academica/crud-formacion_academica.component.ts
- src/app/pages/formacion_academica/crud-formacion_academica/form-formacion_academica.ts
- src/app/pages/info_persona/crud-info_persona/crud-info_persona.component.ts
hotfix: Ajuste menor formularios experiencia_laboral formacion_academica ZonaHorariaFechas InfoPersona
> hotfix: Ajuste menor formularios experiencia_laboral formacion_academica ZonaHorariaFechas InfoPersona

- src/app/pages/admision/asignar_documentos_descuentos/asignar_documentos_descuentos.component.ts
- src/app/pages/admision/def_suite_inscrip_programa/def-suite-inscrip-programa.component.html
- src/app/pages/admision/def_suite_inscrip_programa/def-suite-inscrip-programa.component.ts
- src/app/pages/inscripcion/inscripcion_general/inscripcion_general.component.html
- src/app/pages/inscripcion/inscripcion_general/inscripcion_general.component.scss
- src/app/pages/inscripcion/inscripcion_general/inscripcion_general.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
- https://github.com/udistrital/sga_cliente/issues/1117
- Se ajusta componente definición suite programa para consultar, guardar, y editar suite para un programa particular teniendo en cuenta el tipo de inscripción.
- El periodo en ese componente ahóra está habilitado para elegir otro periodo a parte del actual.
- Se ajusta inscripción general para que consuma la definición de la suite para cada programa en específico, se tiene en cuenta: periodo, programa, tipoInscripción.
- La visualización de los tags y su respectiva carga de porcentaje ahora es dinámico, van en función de los tags que se hayan seleccionado en el apartado de definición de Suite.
- Se saca idiomas de formación académica, y se le genera nuevo tag y vista única para ese formulario.
- Se ajusta el acumulado porcentual para …
> feat: #1117 implementación suite programa por tags

- src/app/pages/info_persona/view-info-persona/view-info-persona.component.html
- src/app/pages/info_persona/view-info-persona/view-info-persona.component.ts
- src/app/pages/inscripcion/crud-inscripcion_multiple/crud-inscripcion_multiple.component.ts
- src/app/pages/inscripcion/inscripcion_general/inscripcion_general.component.html
- src/app/pages/inscripcion/inscripcion_general/inscripcion_general.component.ts
- https://github.com/udistrital/sga_cliente/issues/1186
- Segun mockup se añade info correo, telefono, fecha nacimiento, lugar nacimiento, direccion
- Se ajusta carga de suite cuando ya está inscrito para que cargue enfasis automáticamente y permita en la vista perfil(resumen inscripcion) ver la información segun los tags seleccionados.
> feat: #1186 Se añade info básica a vista perfil(resumen inscripcion)

- src/app/pages/reportes/visualizacion/visualizacion.component.html
- src/app/pages/reportes/visualizacion/visualizacion.component.scss
management: despliegue prueba reportes
> management: despliegue prueba reportes 

- src/app/pages/reportes/visualizacion/visualizacion.component.html
management: despliegue reportes
> management: despliegue reportes 

- src/app/pages/reportes/visualizacion/visualizacion.component.html
- src/app/pages/reportes/visualizacion/visualizacion.component.ts
> management: reportes 

- src/app/@core/data/models/diccionario/diccionario.ts
- src/app/@theme/components/dinamicform/dinamicform.component.html
- src/app/@theme/components/index.ts
- src/app/@theme/components/ng2-st-button/ng2-st-button.component.ts
- src/app/@theme/theme.module.ts
- src/app/pages/pages-routing.module.ts
- src/app/pages/plan-trabajo-docente/asignar-ptd/asignar-ptd.component.html
- src/app/pages/plan-trabajo-docente/asignar-ptd/asignar-ptd.component.scss
- src/app/pages/plan-trabajo-docente/asignar-ptd/asignar-ptd.component.spec.ts
- src/app/pages/plan-trabajo-docente/asignar-ptd/asignar-ptd.component.ts
- src/app/pages/plan-trabajo-docente/forms/form-info_docente.ts
- src/app/pages/plan-trabajo-docente/horario-carga-lectiva/horario-carga-lectiva.component.html
- src/app/pages/plan-trabajo-docente/horario-carga-lectiva/horario-carga-lectiva.component.scss
- src/app/pages/plan-trabajo-docente/horario-carga-lectiva/horario-carga-lectiva.component.spec.ts
- src/app/pages/plan-trabajo-docente/horario-carga-lectiva/horario-carga-lectiva.component.ts
- src/app/pages/plan-trabajo-docente/plan-trabajo-docente-routing.module.ts
- src/app/pages/plan-trabajo-docente/plan-trabajo-docente.component.ts
- src/app/pages/plan-trabajo-docente/plan-trabajo-docente.module.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
- https://github.com/udistrital/sga_cliente/issues/872
- Creación de módulo Plan Trabajo Docente, en particular el componente de asignación de plan en rol coordinador.
- Creación de componente horario interactivo con funcionalidad drag and drop evitando superposición de carga lectiva por hora y día.
- Creado dinámico de carga, edición y borrado.
- Conteo de horas carga lectiva.
> feat: #872 creación módulo ptd componente asignación ptd

- package-lock.json
- src/app/@core/data/espacios_academicos.service.ts
- src/app/@theme/components/index.ts
- src/app/@theme/components/ng2-st-check/ng2-st-check.component.ts
- src/app/@theme/theme.module.ts
- src/app/pages/pages.component.ts
- src/app/pages/plan-trabajo-docente/plan-trabajo-docente-routing.module.ts
- src/app/pages/plan-trabajo-docente/plan-trabajo-docente.module.ts
- src/app/pages/plan-trabajo-docente/preasignacion/dialogo-preasignacion/dialogo-preasignacion.component.html
- src/app/pages/plan-trabajo-docente/preasignacion/dialogo-preasignacion/dialogo-preasignacion.component.scss
- src/app/pages/plan-trabajo-docente/preasignacion/dialogo-preasignacion/dialogo-preasignacion.component.spec.ts
- src/app/pages/plan-trabajo-docente/preasignacion/dialogo-preasignacion/dialogo-preasignacion.component.ts
- src/app/pages/plan-trabajo-docente/preasignacion/preasignacion.component.html
- src/app/pages/plan-trabajo-docente/preasignacion/preasignacion.component.scss
- src/app/pages/plan-trabajo-docente/preasignacion/preasignacion.component.spec.ts
- src/app/pages/plan-trabajo-docente/preasignacion/preasignacion.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
- src/environments/environment.ts
feat: Desarrollo de la interfaz de preasignación de plan de trabajo docente. #1277
> feat: Desarrollo de la interfaz de preasignación de plan de trabajo docente. #1277

- src/app/pages/plan-trabajo-docente/horario-carga-lectiva/horario-carga-lectiva.component.html
- src/app/pages/plan-trabajo-docente/horario-carga-lectiva/horario-carga-lectiva.component.scss
- src/app/pages/plan-trabajo-docente/horario-carga-lectiva/horario-carga-lectiva.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
feat: Integración de la consulta de disponibilidad del espacio físico. #1308 #1300
> feat: Integración de la consulta de disponibilidad del espacio físico. #1308 #1300

- src/app/pages/plan-trabajo-docente/horario-carga-lectiva/horario-carga-lectiva.component.html
- src/app/pages/plan-trabajo-docente/horario-carga-lectiva/horario-carga-lectiva.component.ts
feat: Funcionalidad de creación de actividades por parte del rol docente para carga docente. #1297
> feat: Funcionalidad de creación de actividades por parte del rol docente para carga docente. #1297

- src/app/pages/plan-trabajo-docente/asignar-ptd/asignar-ptd.component.ts
- src/app/pages/plan-trabajo-docente/horario-carga-lectiva/horario-carga-lectiva.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
- src/environments/environment.ts
- https://github.com/udistrital/sga_cliente/issues/1325
- Ajuste para recibir copia de actividades en rol rol docente.
- Se añade en el guardado del plan, la información a descartar cuando se hace copia plan
> feat: #1325 copia actividades plan docente

- src/app/@core/data/plan_trabajo_docente.service.ts
- src/app/pages/plan-trabajo-docente/asignar-ptd/asignar-ptd.component.html
- src/app/pages/plan-trabajo-docente/asignar-ptd/asignar-ptd.component.ts
- src/app/pages/plan-trabajo-docente/horario-carga-lectiva/horario-carga-lectiva.component.html
- src/app/pages/plan-trabajo-docente/horario-carga-lectiva/horario-carga-lectiva.component.ts
- src/app/pages/plan-trabajo-docente/plan-trabajo-docente.module.ts
- src/app/pages/plan-trabajo-docente/preasignacion/dialogo-preasignacion/dialogo-preasignacion.component.html
- src/app/pages/plan-trabajo-docente/preasignacion/dialogo-preasignacion/dialogo-preasignacion.component.ts
- src/app/pages/plan-trabajo-docente/preasignacion/preasignacion.component.html
- src/app/pages/plan-trabajo-docente/preasignacion/preasignacion.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
- https://github.com/udistrital/sga_cliente/issues/1326
- Ajuste de flujo de interacción entre rol docente y coordinación en la creación y definición de plan trabajo docente.
- :warning: Se trabajó a la par con mid -> requiere actualizar tambien. Nota: Se hacen ajustes en preasignación también para mayor consistencia en el flujo, Se crea también el servició de plan trabajo docente
> feat: #1326 flujo planTrabajoDocente Coord/Docente

- src/app/pages/plan-trabajo-docente/asignar-ptd/asignar-ptd.component.html
- src/app/pages/plan-trabajo-docente/asignar-ptd/asignar-ptd.component.scss
- src/app/pages/plan-trabajo-docente/asignar-ptd/asignar-ptd.component.ts
- src/environments/environment.ts
- https://github.com/udistrital/sga_cliente/issues/1339
- Se consume el controlador que genera los reportes en excel de horarios de carga de docente
> feat: #1339 consumo controlador generacion reportes excel

- src/app/pages/reportes/visualizacion/visualizacion.component.ts
- src/environments/environment.dev.ts
- src/environments/environment.prod.ts
- src/environments/environment.test.ts
- src/environments/environment.ts
feat: ajuste para discriminar los reportes segun ambiente #1348
> feat: ajuste para discriminar los reportes segun ambiente #1348

- src/app/pages/plan-trabajo-docente/asignar-ptd/asignar-ptd.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
- https://github.com/udistrital/sga_cliente/issues/1344
> feat: #1344 ajuste manejo de respuesta controlador generación reporte ptd

- src/app/pages/plan-trabajo-docente/asignar-ptd/asignar-ptd.component.ts
- src/app/pages/plan-trabajo-docente/forms/form-verificar_ptd.ts
- src/app/pages/plan-trabajo-docente/horario-carga-lectiva/horario-carga-lectiva.component.html
- src/app/pages/plan-trabajo-docente/verificar-ptd/verificar-ptd.component.html
- src/app/pages/plan-trabajo-docente/verificar-ptd/verificar-ptd.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
- https://github.com/udistrital/sga_cliente/issues/1367
> feat: #1367 funcionalidad verificar PTD, lista y aprobacion

- src/app/pages/plan-trabajo-docente/asignar-ptd/asignar-ptd.component.ts
- src/app/pages/plan-trabajo-docente/horario-carga-lectiva/horario-carga-lectiva.component.ts
- src/app/pages/plan-trabajo-docente/verificar-ptd/verificar-ptd.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
- src/environments/environment.ts
- https://github.com/udistrital/sga_cliente/issues/1373
- Se ajusta el formulario selector de espacio físico para usar el controlador desarrollado, ahora se filtra por proyecto cuando se asigna carga lectiva (asignaturas)
> feat: #1373 Consumo controlador espaciosfisico dependecia

- src/app/@core/pipes/safeUrl.pipe.ts
- src/app/pages/plan-estudios/plan-estudios-routing.module.ts
- src/app/pages/plan-estudios/plan-estudios.module.ts
- src/app/pages/plan-estudios/summary-planes-estudio/summary-planes-estudio.component.html
- src/app/pages/plan-estudios/summary-planes-estudio/summary-planes-estudio.component.scss
- src/app/pages/plan-estudios/summary-planes-estudio/summary-planes-estudio.component.ts
- src/app/pages/plan-estudios/visualizar-documento-plan/visualizar-documento-plan.component.html
- src/app/pages/plan-estudios/visualizar-documento-plan/visualizar-documento-plan.component.scss
- src/app/pages/plan-estudios/visualizar-documento-plan/visualizar-documento-plan.component.spec.ts
- src/app/pages/plan-estudios/visualizar-documento-plan/visualizar-documento-plan.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
feat: udistrital/sga_cliente#1448
Se crean dos funciones para generar el documento del plan de estudio
- Una función para consultar el endpoint del sga_mid que genera el documento tomando como entrada del componente de visualización el JSON con la estructura de visualización.
- Una función que espera el id del plan de acción para consultar el endpoint que retorna el JSON con la estructura de visualización y posteriormente se consulta el endpoint que genera el documento.
> feat: udistrital/sga_cliente#1448 creado dialogo para visualizar el documento pdf del plan de estudios

- src/app/pages/gestion-horarios/gestion-horarios.module.ts
- src/app/pages/gestion-horarios/registro-horarios/registro-horarios.component.html
- src/app/pages/gestion-horarios/registro-horarios/registro-horarios.component.scss
- src/app/pages/gestion-horarios/registro-horarios/registro-horarios.component.ts
- src/app/pages/plan-trabajo-docente/horario-carga-lectiva/horario-carga-lectiva.component.html
- src/assets/i18n/en.json
- src/assets/i18n/es.json
feat: creación de componente asignación horaria base #1433 segun mockup
> feat: creación de componente asignación horaria base #1433 segun mockup

- src/app/pages/plan-estudios/creacion-plan-estudios/creacion-plan-estudios.component.ts
- src/app/pages/plan-estudios/plan-estudio-base/plan-estudio-base.component.ts
- src/app/pages/plan-estudios/plan-estudios-routing.module.ts
- src/app/pages/plan-estudios/revisar-planes-estudio/revisar-planes-estudio.component.html
- src/app/pages/plan-estudios/revisar-planes-estudio/revisar-planes-estudio.component.scss
- src/app/pages/plan-estudios/revisar-planes-estudio/revisar-planes-estudio.component.spec.ts
- src/app/pages/plan-estudios/revisar-planes-estudio/revisar-planes-estudio.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
> feat: udistrital/sga_cliente#1463 Agregado módulo de reporte filtrado por rol y vinculación tercero

- src/app/pages/plan-estudios/creacion-plan-estudios/creacion-plan-estudios.component.ts
- src/app/pages/plan-estudios/plan-estudio-base/plan-estudio-base.component.ts
- src/app/pages/plan-estudios/plan-estudios-routing.module.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
feat: udistrital/sga_cliente#1462
> feat: udistrital/sga_cliente#1462 Agregado filtro por rol y tercero id

- src/app/@core/utils/zip-manager.service.ts
- src/app/pages/admision/evaluacion-documentos-inscritos/evaluacion-documentos-inscritos.component.ts
- src/app/pages/descuento_academico/view-descuento_academico/view-descuento_academico.component.ts
- src/app/pages/documento_programa/view-documento_programa/view-documento_programa.component.ts
- src/app/pages/experiencia_laboral/view-experiencia_laboral/view-experiencia_laboral.component.ts
- src/assets/i18n/es.json
- https://github.com/udistrital/sga_cliente/issues/1477
> feat: #1477 replicar hotfix issue_1444 documentos_admisiones tercero_inscripcion

- src/app/pages/plan-trabajo-docente/preasignacion/dialogo-preasignacion/dialogo-preasignacion.component.html
- src/app/pages/plan-trabajo-docente/preasignacion/dialogo-preasignacion/dialogo-preasignacion.component.ts
- src/app/pages/plan-trabajo-docente/preasignacion/preasignacion.component.html
- src/app/pages/plan-trabajo-docente/preasignacion/preasignacion.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
- https://github.com/udistrital/sga_cliente/issues/1465
- https://github.com/udistrital/sga_cliente/issues/1478
- revisa si el esp_acad modular para preasignacion docente.
- mini fix, tabla no actualizaba a vacío cuando se eliminaba el ultimo registro.
> feat: #1465 #1474, ajuste preasignacion espacios academicos modulares

- src/app/pages/produccion_academica/crud-produccion_academica/crud-produccion_academica.component.html
- src/app/pages/produccion_academica/crud-produccion_academica/crud-produccion_academica.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
- https://github.com/udistrital/sga_documentacion/issues/19
> feat: udistrital/sga_documentacion#19 revisión y ajustes formularios de preinscripción

- src/app/@core/utils/zip-manager.service.ts
- src/app/@theme/components/dinamicform/dinamicform.component.html
- src/app/@theme/components/dinamicform/dinamicform.component.scss
- src/app/@theme/components/dinamicform/dinamicform.component.ts
- src/app/@theme/components/video-modal/video-modal.component.html
- src/app/pages/dashboard/dashboard.module.ts
- src/app/pages/dashboard/news/news.component.html
- src/app/pages/descuento_academico/list-descuento_academico/list-descuento_academico.component.html
- src/app/pages/info_persona/crud-info_persona/crud-info_persona.component.html
- src/app/pages/inscripcion/inscripcion_general/inscripcion_general.component.html
- src/app/pages/modalidad/crud-modalidad/crud-modalidad.component.html
- src/app/pages/produccion_academica/view-produccion_academica/view-produccion_academica.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
- src/environments/environment.dev.ts
- src/environments/environment.test.ts
- https://github.com/udistrital/sga_documentacion/issues/36
> feat: udistrital/sga_documentacion#36 ajuste docs produccion academica y build por set()

- src/app/pages/proyecto_academico/crud-proyecto_academico/crud-proyecto_academico.component.html
- src/app/pages/proyecto_academico/crud-proyecto_academico/crud-proyecto_academico.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
- https://github.com/udistrital/sga_documentacion/issues/133
> hotfix: udistrital/sga_documentacion#133 agregado de select dependencia oikos

- src/app/pages/calendario-academico/administracion-calendario/administracion-calendario.component.ts
- src/app/pages/calendario-academico/calendario-academico-routing.module.ts
- https://github.com/udistrital/sga_documentacion/issues/143
> fix: udistrital/sga_documentacion#143 select multiple proyecto para usuario con varias vinculaciones

- src/app/pages/admision/criterio_admision/criterio_admision.component.ts
udistrital/sga_documentacion#218
Se soluciona el bug que evitaba la eliminación de criterios para un proyecto curricular al deseleccionarlos.
> fix: solución error que evitaba la elimianción de requisitos

- src/app/pages/admision/criterio_admision/criterio_admision.component.ts
udistrital/sga_documentacion#218
Se soluciona el bug que evitaba la eliminación de criterios para un proyecto curricular al deseleccionarlos.
> HotFix: solución error que evitaba la eliminación de requisitos

- src/app/@theme/components/dinamicform/dinamicform.component.scss
- src/app/@theme/components/new-tercero/new-tercero.component.ts
- src/app/pages/experiencia_laboral/crud-experiencia_laboral/crud-experiencia_laboral.component.ts
- src/app/pages/experiencia_laboral/crud-experiencia_laboral/form-experiencia_laboral.ts
- src/app/pages/formacion_academica/crud-formacion_academica/crud-formacion_academica.component.ts
- src/app/pages/formacion_academica/crud-formacion_academica/form-formacion_academica.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
udistrital/sga_documentacion/issues/253
> Hotfix/issue#253 manejo de búsqueda de nit exceptuando digito de verificación

- src/app/pages/inscripcion/crud-inscripcion_multiple/crud-inscripcion_multiple.component.ts
- udistrital/sga_documentacion#266
> fix: udistrital/sga_documentacion#266 inclusión codigo interno generacion recibo

- src/app/pages/admision/listado_aspirantes/listado_aspirante.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
udistrital/sga_documentacion/issues/285
> feat: Se agrega reglas para restringuir cambios de estados aspirante

- src/app/@theme/components/dinamicform/dinamicform.component.ts
- src/app/pages/propuesta_grado/crud-propuesta_grado/crud-propuesta_grado.component.ts
- https://github.com/udistrital/sga_documentacion/issues/316
> fix: ajuste doc y selects propuesta grado

- src/app/pages/info_persona/view-info-persona/view-info-persona.component.ts
udistrital/sga_documentacion#331
> Se soluciona bug que deja pantalla cargando cuando no encuentra alguna info del aspirante

- src/app/pages/admision/evaluacion-documentos-inscritos/evaluacion-documentos-inscritos.component.ts
udistrital/sga_documentacion#331
> Se corrige el periodo que se muestra en detalle de inscripcion para aspirantes

- src/app/pages/admision/evaluacion-documentos-inscritos/evaluacion-documentos-inscritos.component.ts
udistrital/sga_documentacion#331
> Fix periodo en sessionStorage

- src/app/pages/informacion_contacto/crud-informacion_contacto/crud-informacion_contacto.component.ts
- src/app/pages/inscripcion/inscripcion_general/inscripcion_general.component.ts
- https://github.com/udistrital/sga_documentacion/issues/357
> fix: udistrital/sga_documentacion#357 ajuste loading crud y cálculo porcentaje

- src/app/pages/dashboard/dashboard.module.ts
- src/app/pages/dashboard/news/news.component.html
- src/app/pages/dashboard/news/news.component.scss
- src/assets/i18n/en.json
- src/assets/i18n/es.json
> feat: actualizar dashboard con mensaje de bienvenida

- src/app/pages/inscripcion/crud-inscripcion_multiple/crud-inscripcion_multiple.component.ts
- udistrital/sga_documentacion#413
> fix: udistrital/sga_documentacion#413 Ajusta consulta parametros anio anterior si periodo es 1

- src/app/pages/documento_proyecto/select-documento-proyecto/select-documento-proyecto.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
udistrital/sga_documentacion#456
Se crea una función para validar el rol del usuario quue desea administrar los documentos.
> fix: Validación de rol para la creación de documentos

- src/app/@core/store/services/list.service.ts
Se corrige peticion a endpoint de api_crud del siciud para obtener todos los grupos de investigación
> fix: Correccion peticion a api crud siciud

- src/app/pages/propuesta_grado/crud-propuesta_grado/crud-propuesta_grado.component.ts
se corrige comportamiento del formulario para que se muestren las opciones del select correctamente
> fix: se corrige comportamiento del formulario propuesta grado

- src/app/pages/admision/asignar_documentos_descuentos/asignar_documentos_descuentos.component.html
- src/app/pages/descuento_proyecto/select-descuento-proyecto/select-descuento-proyecto.component.ts
- Modificación de lógica de visualización del módulo de descuentos, se basa en la lectura de los roles asigandos.
- Roles con permiso de lectura: 'VICERRECTOR', 'ASESOR_VICE', 'ADMIN_SGA', 'ASIS_PROYECTO', 'JEFE_DEPENDENCIA'
- Roles con permiso de modificación: ADMIN_SGA, VICERRECTOR
> feat: Visualizacion de módulo de descuentos para roles específicos
